### ISSUE TITLE
Mejorar vista de análisis

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#123]
**Tiempo estimado: 1 hora 16 min**

Realizar una mejora en la disposicion de elementos del dashboard de análisis

**Comment by alemerpal** [comment]
Trabajo realizado (07/03) :

- Se han mejorado los estilos de la vista de análisis
- Se ha integrado la vista de top repositories en análisis

**Comment by dangalmar** [comment]
La tarea ha sido completada con exito
