### ISSUE TITLE
Redirección de botones y navbar

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#124]
**Tiempo estimado: 33 min**

Mejorar la redireccion de la barra de navegacion y los botones de accion y formulario

**Comment by marizqlav** [comment]
Diseño de con librería Swat tanto para register de candidate como pararepresentante y para el logout de ambos y el de navbar
Ademas de que he añadido para que el navbar cuando no estes logeado solo te aparezca setting e información, junto a la redirección de la barra de navegación.

**Comment by dangalmar** [comment]
Quitar la opción de perfil del navbar

**Comment by marizqlav** [comment]
La opción de perfil del navbar se ha quitado porque ya se encuentra al fondo del mismo

**Comment by dangalmar** [comment]
Todo correcto
