### ISSUE TITLE
Mejorar formulario de analisis

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#125]
**Tiempo estimado: 37 min**

Mejorar formulario de analisis.

**Comment by albdomrui20** [comment]
**Tiempo real: 7 min**

**Trabajo realizado:**
- Los análisis existentes de redirigen a dicho análisis
- El resto de mensajes de error son más visibles.
- Añadido botón en el listado para volver al formulario
Hash del commit: afc596b1dead411ffb8209ed21b0630369b35f89

**Comment by dangalmar** [comment]
Funciona perfectamente el formulario
