### ISSUE TITLE
Finalizar sistema de login y logout

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#127]
**Tiempo estimado: 1 hora**

Tareas a realizar:
- [x] Finalizar login y logout (sobretodo que se haga de forma automatica despues del registro)
- [x] cargar datos de sesion en navbar
- [x] cargar datos de sesion en perfil
- [x] probar pipeline de registro, logout, login y logout de nuevo (candidato y representante)

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**
 - Revisión login/register/logout.
 - cargar datos de sesión en navbar.
 - cargar datos de sesión en perfil que antes no se cargaban.
 - probar pipeline de registro, logout, login y logout de nuevo (candidato y representante)

hash del commit: 5778d2d540a3ee1207f2601b41a35adc93505400

**Comment by carlos-bermejo** [comment]
Error encontrado en navbar. Procedo a arreglarlo.

**Comment by carlos-bermejo** [comment]
**Problemas arreglados:**

- Arreglos en algunas vistas.
- Error de barra de navegación arreglado.

hash del commit: 0b5528658187ed0c459ac032840377c44e7577f9

**Comment by carlos-bermejo** [comment]
Tiempo de finalización: 1 hora y 38 minutos.

**Comment by carlos-bermejo** [comment]
Error de **número de teléfono** correjido.
Commit: 72502e897dc88ff32c2951c3aa6a52eb048cb7bc

**Comment by dangalmar** [comment]
Revisado y completado
