### ISSUE TITLE
Crear storyboard

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#129]
|**Tiempo estimado** |**2h**|
|-|-|

Será necesario crear un storyboard siguiendo las indicaciones de la píldora teórica "[Theory Pill - Replanning, Story Boards, and Expenses_Revenues Estimation](https://videos.us.es/media/ISPP_2024_Replanning_StoryBoards_RevenuesExpensesEstimations/1_xi1mwa7k)".

Tener en cuenta que este storyboard va dirigido a realizar un vídeo promocional de IT Talent.

**Comment by RukisRo** [comment]
Terminado, pendiente de Feedback.

**Comment by RukisRo** [comment]
[Enlace al storyboards de candidatos](https://www.canva.com/design/DAF_JBr6sf4/LQh64uMkyODEwBf6yWFNIA/edit?utm_content=DAF_JBr6sf4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by IsmaelHerrera2000** [comment]
Storyboards terminados correctamente.
