### ISSUE TITLE
Crear presentación de retrospectiva

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#130]
|**Tiempo estimado por persona** |**4h**|
|-|-|

Será necesario tener una presentación para la sesión de retrospectiva del 12/03/2024, para ello se tendrán en cuenta los siguientes puntos:

- Tablas con horas.
- Tareas que hemos hecho.
- Rendimiento del equipo.
- Mecánicas de trabajo.
- Commitment agreement, ¿Se cumple? ¿Modificaciones?

**Comment by RukisRo** [comment]
Las diapositivas se han realizado y expuesto en clase correctamente
