### ISSUE TITLE
Pasar documentación a MarkDownx

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#132]
|**Tiempo estimado** |**2h**|
|-|-|

Pasaremos toda nuestra documentación que está actualmente en Google Drive a formato MarkDownx, para luego asignarla al docusaurio.

**Comment by Francisco-David** [comment]
Actualmente en proceso en local, toda actualización en https://github.com/Francisco-David/ITTalent-Wiki/

**Comment by IsmaelHerrera2000** [comment]
Toda la documentación está en MarkDown tanto en la base de conocimiento común como en la carpeta /docs
