### ISSUE TITLE
Crear action formatter

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#134]
|**Tiempo estimado** |**1h**|
|-|-|

Será necesario crear un GitHub action que permita formatear todo el código a un estándar.

**Comment by Moffinguer** [comment]
A la espera de feedback del resto del equipo cuando vayan probandolo @IsmaelHerrera2000

**Comment by JaviFdez7** [comment]
Formatter mergeado a develop correctamente
