### ISSUE TITLE
Crear formularios para usuarios piloto

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#135]
**Tareas a realizar:**

- Crear formulario para usuarios candidato.
- Crear formulario para usuarios representante (empresas).

**Comment by carlos-bermejo** [comment]
**Tareas realizadas:**

- Crear formulario para usuarios candidato.
- Crear formulario para usuarios representante (empresas).

**Comment by carlos-bermejo** [comment]
Los enlaces a los formularios son los siguientes:

- formulario candidatos: [https://forms.office.com/Pages/DesignPageV2.aspx?prevorigin=shell&origin=NeoPortalPage&subpage=design&id=TmhK77WBHEmpjsezG-bEaaHRqMaG-7BNku5m2TkjUP9UOUJXWkZJTEsxTDFZMUY4SDZEOFpTOEtSTy4u](url)
- formulario representantes: [https://forms.office.com/Pages/DesignPageV2.aspx?prevorigin=shell&origin=NeoPortalPage&subpage=design&id=TmhK77WBHEmpjsezG-bEaaHRqMaG-7BNku5m2TkjUP9UQTMxT0xVMDRTSE5KSEw2SzI0SFNVREFURi4u](url)

**Comment by IsmaelHerrera2000** [comment]
Formularios creados correctamente.
