### ISSUE TITLE
enviroment mongo url 

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#136]
### Explicación
Se debe poner la url de mongo como variable de entorno para que pueda ser desplegado en produccion. Adjunto los archivos que comentó fernando.
1. En app.ts el `host` debe ser una variable de entorno, por defecto el localhost.
Estilo `const swaggerHost= process.env.HOST?? "localhos..."`
```js
const swaggerDefinition = {
  info: {
    title: 'IT-Talent backend',
    version: '1.0.0',
    description: 'This is'
  },
  host: 'backend-dot-italent-415216.oa.r.appspot.com'
};
```
3. En el archivo de db mongoURL debe ser una variable de entorno
```js
import mongoose from 'mongoose';

export async function connectToMongoDB() {
  const mongoUrl = 'mongodb+srv://fernandomateosfermatgom:ispDB204@ispp-db.c0mwv5n.mongodb.net/?retryWrites=true&w=majority&appName=ispp-db';
  const dbName = 'ispp-db';

  try {
    // Connect to MongoDB
    await mongoose.connect(`${mongoUrl}/${dbName}`);

    console.log('Successful connection to MongoDB');

    const db = mongoose.connection;

    // Check if the database already exists
    const collections = await db.db.collections();
    const dbExists = collections.some((collection) => collection.collectionName === dbName);

    // If the database doesn't exist, create it
    if (!dbExists) {
      console.log(`Database ${dbName} created successfully`);
    } else {
      console.log(`The database ${dbName} already exists`);
    }

    // The script for populating the database will go here.
  } catch (error) {
    console.error('Error connecting to MongoDB:', error);
  }
}
```

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by andresdominguezruiz** [comment]
**Estimación del tiempo:** 30 minutos
**Trabajo realizado:**

- Nuevas variables de entorno y valores por defecto

**Comment by motero2k** [comment]
Revisado y cerrado
