### ISSUE TITLE
user and favorites validation

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#137]
### Explicación
Refactorizacion de código. En el controlador de user no debe haber validaciones. Las validaciones se deben meter como middelwares en el routes.
```js
app.get("/path", userValidation1, userController);
````
En userValidator.js
```js
//pseudocodigo
userValidation1(){
if(no se cumple validacion) res.send error 3XX ; return;
next() // pasa al siguiente middelware
```

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He mirado en internet como hacer validadores en express
- [x] Los codigos de error y el mensaje siguen el estandar definido
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by carzarrei** [comment]
Teniendo en cuenta la explicación, creo que en refctorizar todos los middlewares de user más comprobar su correcto funcionamiento, en total estimo entre 1h - 1,5h para la tarea completa. En caso de tener que añadir más validaciones (por ejemplo al historial y favoritos) quizá el tiempo asciende hasta las 2h. Bajo ningun caso espero tardar más de 2,5h en esta tarea.

**Comment by carzarrei** [comment]
Se han realizado los cambios, pero ha surgido un error inesperado al hacer run, estoy pendiente de probarlo y subirlo. Tiempo consumido, 1,5h.
Ficheros con cambios (modulo user):
userMiddleware.ts
userController.ts
routes.ts

**Comment by motero2k** [comment]
el estandar de response lo debe definir @FJMonteroInformatica #142

**Comment by carzarrei** [comment]
Se ha probado toda la funcionalidad refactorizada de User, pongo la tarea en revision.

Se ha detectado además un error con el JWT cuando se lanza una petición con un token antiguo (expirado), que lanza un error que para la aplicación. Queda pendiente de revisarlo

**Comment by motero2k** [comment]
Revisada PR y completo. Buen trabajo!
