### ISSUE TITLE
user  and favorites endpoints

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#138]
### Explicación
Refactorizacion de código. Pensar si estan bien los endpoints de usuario siguiendo los principios de apiREST. Actualizar el swagger en consecuencia. De deben arreglar los tags y ademas poner buenos ejemplos de todo. 
Mirar si se puede poner los token de jwtoken

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He mirado en internet como hacer enpoints siguiendo los principios apiREST
- [x] He actualizado los endpoints en codigo y swagger de usuario
- [x] He actualizado los endpoints en codigo y swagger de favoritos
- [x] He arreglado los tags del swagger y puesto el token si se puede.
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by carzarrei** [comment]
No me queda claro qe quieres decir con refactorización de endpoints, quiero decir, te refieres a cambiar las rutas y sus parámetros en caso de ser mas conveniente? (por ejemplo añadir un id como parámetro a una ruta en vez de usar solo el id del usuario actual)
Sobre el token de jwt, que te refieres con ponerlo, añadirlo a las validaciones?
Y sobre los tags, entiendo que son del swagger no?

**Comment by motero2k** [comment]
Te pongo un ejemplo /history/favorites no tiene mucho sentido. siempre suele ser coleccion/{id}/coleccion/{id} (máximo dos niveles)
en todo caso puede ser /history/?favorite=true&user=username

Es un ejemplo. Pero en principio los endpoints de history, user y experience se pueden poner un poco mas estándar.

**Comment by carzarrei** [comment]
Estimación: Contando que el estándar de endpoints ya está definido, cuento con aproximadamente 2 horas estimadas para realizar los cambios tanto en las rutas como en los parámetros y funcionamiento de los metodos afectados. En cualquier caso dispongo de un total de 3,5 horas dado que la otra tarea asignada se ha acabado en 1,5 h en total.

**Comment by carzarrei** [comment]
Se ha realizado el trabajo en menor tiempo del estimado. Pues el módlo de user ya cumplia con el estándar que se ha seguido.
