### ISSUE TITLE
professional experience endpoints

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#139]
### Explicación
Refactorizacion de código. Pensar si estan bien los endpoints de professional-experience siguiendo los principios de apiREST. Actualizar el swagger en consecuencia. De deben arreglar los tags y ademas poner buenos ejemplos de todo. 
Renombar a professional-experience

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He mirado en internet como hacer enpoints siguiendo los principios apiREST
- [x] He actualizado los endpoints en codigo y swagger
- [x] He arreglado los tags del swagger.
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by FJMonteroInformatica** [comment]
Estimo que la tarea me llevará alrededor de 1,5h. Sugiero que se unifiquen esta issue y #140. Están muy relacionadas e incluso se repiten en algún punto.

**Comment by FJMonteroInformatica** [comment]
Se ha refactorizado el código y modificados los endpoints siguiendo los principios REST. Falta actualizar swagger en consecuencia.

**Comment by FJMonteroInformatica** [comment]
Se ha actualizado Swagger atendiendo a los cambios en los endpoints.

**Comment by motero2k** [comment]
Revisada y cerrada. Buen trabajo
