### ISSUE TITLE
profesional experience module

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#140]
### Explicación

Refactorizacion de código. 
- Cambiar experience por profesional experience y **sacarlo a un modulo** como favorites para tener todo homogeneo.
- Cambiar los **enpoints** para que sigan los principios REST. Usando parámetros donde sea necesario.
- En el controlador de professional-experience no debe haber **validaciones**. Las validaciones se deben meter como middelwares en el routes.
- Se deben poder listar todas las experiencias de un usuario.
```js
app.get("/path", experienceValidation1, experienceController);
````
En experienceValidator.js
```js
//pseudocodigo
experienceValidation1(){
if(no se cumple validacion) res.send error 3XX ; return;
next() // pasa al siguiente middelware
```

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He mirado en internet como hacer validadores en express y endpoints estandarizados
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by FJMonteroInformatica** [comment]
Estimo que la tarea me llevará alrededor de 30 minutos, ya que algunas cosas están hechas. Ya existen middlewares para las experiencias profesionales y el método para listar todas las experiencias de un usuario.

**Comment by motero2k** [comment]
Revisada y cerrada.
