### ISSUE TITLE
analysis refactor

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#141]
### Explicación
- Refactorizacion de código. En el controlador de user no debe haber validaciones. Las validaciones se deben meter como middelwares en el routes.
- Buscar nuevos datos interesantes que extraer de GH para hacer mejores analisis.
```js
app.get("/path", analisysValidation1, analysisController);
````
En analysisValidator.js
```js
//pseudocodigo
analysisValidation1(){
if(no se cumple validacion) res.send error 3XX ; return;
next() // pasa al siguiente middelware
```

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He mirado en internet como hacer validadores en express
- [x] Refactorizacion completa
- [x] Nuevos datos completos
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by RubenCasal** [comment]
Validator del usuario de github y apikey realizado

**Comment by RubenCasal** [comment]
se ha añadido el porcentaje de uso de los lenguajes mas utilizados

**Comment by RubenCasal** [comment]
se ha arreglado, y ahora devuelve las tecnologías de todos los repositorios, antes solo de los 10 primeros

**Comment by RubenCasal** [comment]
Se ha añadido la descripción de los repositorios, también se hizo en un primer momento las tag de los tópicos del repositorio, pero al hacerse se observo, que casi ningún repositorio lo incluia

**Comment by RubenCasal** [comment]
Se ha añadido el número de issues cerradas por el usuario en los repositorios más recientes. Se hace buscando los asignados de las issues cerradas de un repositorio, si sale el nombre del usuario se contabiliza

**Comment by RubenCasal** [comment]
También se ha intentando hacer que con el número de commits, pero solo se podía sacar los de la rama principal (main) y se ha decidido que añade mucho coste coputacional y además que no es representativo

**Comment by RubenCasal** [comment]
Se ha añadido, el número total de issues que ha cerrado el usuario y la información del repositorio con más issues cerradas

**Comment by RubenCasal** [comment]
Se han actualizado las respuestas de la api, con las plantillas proporcionadas

**Comment by motero2k** [comment]
Revisada y cerrada.
