### ISSUE TITLE
api responses

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#142]
### Explicación
 La api del backend debe devolver los puntos siguiendo un estándar como JSONAPI u otros. Buscar el que se ajuste a nuestras necesidades.

Ejemplo respuesta correcta 200 ok
```json
{
  "links": {
    "self": "http://example.com/articles"
  },
  "data": []
}
````
Se puede crear un archivo ts para ayudar a crear respuestas homogéneas en toda la api. y que todos los validadores usen esa clase.

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He mirado en internet los estándares de respuestas API
- [x] He definido en un documento el estándar que usamos con un ejemplo
- [x] He implementado una respuesta para comprender si funciona correctamente
- [x] He comunicado a mis compañeros del backend como deben cambiar las respuestas
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by FJMonteroInformatica** [comment]
Estimo, teniendo en cuenta que es una tarea crítica y a la que hay que prestar una atención especial, una duración de entre 1,5h y 2h.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Ayudar a entender el formato de ApiResponse
- Solucionar errores junto a Fran

**Comment by FJMonteroInformatica** [comment]
En el siguiente documento explico el estándar que utilizaremos para las respuestas de la API, así como un ejemplo de respuesta válida y uno de error. Además, pongo un par de ejemplos para que sepáis de qué forma utilizar ApiResponse.ts (una clase que ayuda a crear respuestas que sigan el estándar) para modificar todas las respuestas:

https://docs.google.com/document/d/1ic8hODi4lHEGbBsjeMZLme6RomkqbWKVDI8r86g2Njs/edit

**Comment by motero2k** [comment]
Revisado. Buen trabajo!
