### ISSUE TITLE
Correo a empresas 07/03/2024

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#143]
**Tareas a realizar:**

- Búsqueda de contactos a nuevas empresas.
- Envío de nuevo correo a empresas ya contactadas.
- Envío de nuevo correo a nuevas empresas.
- Actualización del registro de usuarios piloto.

**Comment by carlos-bermejo** [comment]
Se han realizado **todas** las tareas. Los correos han sido enviados.

**Comment by IsmaelHerrera2000** [comment]
Tarea terminada correctamente.
