### ISSUE TITLE
Reunión con posibles usuarios pilotos

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#146]
|**Tiempo estimado** |**30 min**|
|-|-|

Se realizará una reunión con una empresa el día 12/03/2024 a las 16:00.

**Comment by JaviFdez7** [comment]
Se ha acordado con la empresa GFT la reunión el día 12/03/2024 a las 16:00.

**Comment by RukisRo** [comment]
Se lleva a cabo la reunión, se acuerda enviar la información para las pruebas del sistema y quedamos a la espera del posible feedback o de otra reunión.

**Comment by IsmaelHerrera2000** [comment]
Reunión realizada, si se vuelve a realizar otra reunión se creará otra issue.
