### ISSUE TITLE
Control de vistas según rol del usuario logueado

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#148]
Una vez que el registro, login y logout estan realizados es necesario que ciertas vistas tengan control de acceso en funcion del rol del usuario logueado.

TAREAS A REALIZAR

- [x] Realizar middlewares de control de acceso para las vistas de perfil y análisis
- [x] Cuando un usuario vaya a realizar un análisis comprobar que está logueado y es representante

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Se han ajustado los botones del navbar acorde al rol

**Comment by dangalmar** [comment]
Las opciones a las que un rol no puede acceder se deben quitar del navbar. Se debe quitar la opcion de análisis para representante

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Se han quitado la opción de análisis para candidato del navbar

**Comment by dangalmar** [comment]
Ahora si
