### ISSUE TITLE
Reparto de tareas Backend

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#149]
- Definir tareas para el equipo
- Redactarlas como issues
- Añadirlas al tablero,  categorizar y priorizar.
- Asignar las tareas

**Comment by motero2k** [comment]
Ya se repartieron las tareas de la semana. Dejo la issue para proximas semanas.

**Comment by Moffinguer** [comment]
Cierro tarea debido a que lleva desde Marzo sin actualizarse
