### ISSUE TITLE
mejorar vista de perfil (candidato y representante)

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#157]
Actualmente las vistas de perfil de candidato y representantes son muy diferentes y visualmente necesitan mejorar en cuanto a estilos

TAREAS A REALIZAR:

- [x] Hacer un diseño de perfil homogeneo entre candidato y representante aunque los campos no sean los mismos
- [x] Homogeneizar el tamaño de letra de ambos perfiles (el tamaño es distinto en cada uno)
- [x] Mejorar la disposicion de elementos del subapartado de developer info

**Comment by alemerpal** [comment]
He adaptado las dos vistas de perfil a movil, estandarizado los estilos y arreglado la barra de navegación. 
[b5df9a4](https://github.com/JaviFdez7/ISPP-G1-Talent/pull/201/commits/b5df9a4547149451eb4efc1e9ebf5f26bc09aaea)
[7c1a71f](https://github.com/JaviFdez7/ISPP-G1-Talent/pull/201/commits/7c1a71fb4e461c642f79ba8f4437502bb625647c)
[2b31e4b](https://github.com/JaviFdez7/ISPP-G1-Talent/pull/201/commits/2b31e4be479251e6e1eae252875a3e9aa3d58d05)

**Comment by dangalmar** [comment]
Revisado y aprobado
