### ISSUE TITLE
Visualizar el historial de análisis y listado de favoritos

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#161]
Se debe mostrar una lista de historiales en las que se pueda filtrar por favoritos y mostrar datos importantes sobre los análisis.

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Se ha añadido un filtro de listado para los historiales de análisis.
- Se han arreglado errores menores en las rutas.
- Se ha actualizado la imagen de fondo.
- Se ha creado un componente "Select.jsx" para futuros selectores.
- Fetching real de historiales.
- Se han traído cambios de backend.

**Trabajo por realizar:**

- Modificar visualización de los historiales.
- Modificar "Latest Histories" del perfil de representante.
- Crear botón de añadir a favoritos.
- Crear entrada del historial de análisis cuando se realiza un análisis.
- Crear botón de borrar entrada del historial.
- Modificar página del dashboard para que se haga fetch de análisis por "id" y no por usuario.

Hash del commit: 18d3792d471823a0eebbd399d13257919f3881c9

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Se ha modificado visualización de los historiales.
- Se ha creado un componente "AnalysisHistoryItem.jsx".
- Se ha arreglado el redireccionamiento al análisis.

**Trabajo por realizar:**

- Crear botón de añadir a favoritos.
- Crear entrada del historial de análisis cuando se realiza un análisis.
- Crear botón de borrar entrada del historial.

Hash del commit: cdf53d95c86a0e29a3552a7c4037d7df235ea558

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Se ha creado un componente "FavoriteButton.jsx".
- Se ha creado un componente "DeleteHistoryButton.jsx".
- Se ha implementado añadir a favoritos desde el dashboard.
- Se ha modificado el apartado y el componente de "Latest Histories" para que funcione.
- Se han arreglado potencialmente los conflictos entre backend y frontend.

**Trabajo por realizar:**

- Configurar la autorización del DELETE mediante un token en "DeleteHistoryButton.jsx".

Hash del commit: a362cbb8cd9140f6afe9a3965aa9a29562a5e314

**Comment by carlos-bermejo** [comment]
Tiempo invertido: 5 horas y 32 minutos.

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Fix del token de acceso.
- Botón de delete funcional.

Tiempo invertido: 29 minutos
Hash del commit: 81a92f28b58821bfe571298862659c297a05a593

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Fix de la automatización del historial al realizar un análisis.

Tiempo invertido: 1 hora
Hash del commit: b39e3783eba688f86940c7e9186d87cbd28b5f86

**Comment by carlos-bermejo** [comment]
Merge con frontend realizado.
Tiempo invertido: 1 hora.
Hash del commit: c91a7b616827ebb30985217a0537e9704583a4ec

**Comment by dangalmar** [comment]
Revisión realizada
