### ISSUE TITLE
Fórmula para #DP

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#162]
Será necesario tener una fórmula para calcular el rendimiento individual durante el pasado entregables(#DP).

**Comment by JaviFdez7** [comment]
Documento de excel en el que se recoge el rendimiento individual del DP: [LINK](https://docs.google.com/spreadsheets/d/1QRk0et-sujj0QRomhRvNnbRG_8q87Eatm1FuGcMnCxg/edit#gid=651073955)
