### ISSUE TITLE
Cargar en sesion el rol del usuario logueado

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#166]
**Tiempo estimado: 20 min**

Es necesario saber el rol del usuario logueado para el control de multitud de funcionalidades y vistas

TAREAS A REALIZAR:

- [x] Cargar los datos de rol en sesion con el AuthContext
- [x] Asegurarse de que se carga el rol correspondiente en el registro de usuario
- [x] Asegurarse que se actualiza el campo rol en el login
- [x] Asegurarse que se actualiza el campo rol en el logout

**Comment by marizqlav** [comment]
He conseguido que aparezca con data.user.role en login(data.access, data.refresh, data.user.role, data.user._id); que cuando se registre aparezca en almacenamiento local el que el rol con el que se inicie se ponga a true

**Comment by marizqlav** [comment]
Me he asegurado de que no estuviesen los datos despues del logout

**Comment by dangalmar** [comment]
Revisado y correcto
