### ISSUE TITLE
Cambio de los tipos de respuesta al nuevo estándar en analisis

### ISSUE THREAD

**Issue by carzarrei** [JaviFdez7/ISPP-G1-Talent#168]
Es necesario cambiar las respuestas en los controladores y validadores de análisis, usuarios e historial.

- [x] He entendido la issue o he comentado cualquier dda sobre la misma
- [x] He dado la estimación de tiempo para la realización del trabajo.
- [x] He actualizado las respuestas en el módulo de analisis
- [x] Se ha realizado el trabajo y pongo la issue en In Review

**Comment by motero2k** [comment]
Revisada y aprobada. Buen trabajo
