### ISSUE TITLE
team explorer

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#181]
### Explicación

Se debe implemetar el algoritmo de recomendacion para la busqueda por equipos #175 . Es necesario terminar antes #180 
RF19. Búsqueda de candidatos:  Los representantes podrán realizar una búsqueda de  candidatos en la ventana “Búsqueda”. Al acceder a esta vista, visualizamos un formulario en el que podremos añadir de 1 a 5 candidatos. Podremos configurar el número de candidatos en todo momento. Para cada candidato añadido deberemos modificar los siguientes campos:

Especialidad

Lenguajes/Tecnologías

Años de experiencia

Estilo de vida

Ubicación del trabajo 

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by RubenCasal** [comment]
La búsqueda de candidatos se realiza de la siguiente manera por el momento:
1. Se pasa un lista de perfiles de candidatos que pide el usuario representante con (lenguajes, tecnologías, años de experiencia, área de la informática), se procesa la lista pasada, para facilitar las tareas posteriores.
2. Se filtran todos los candidatos que cumplen con algún tipo requisito.
3. Se puntúan los candidatos filtrados en el apartado anterior, sumando un punto por cada requisito que cumplan, y se escoge a los mejores para cada perfil.
4. Se pasa la respuesto con el usuario con más puntuación o varios usuarios en caso de empate para cada perfil, y se guarda la recomendación en base de datos.

**Comment by RubenCasal** [comment]
Se ha añadido la funcionalidad findTeamCreatorById y deleteTeamCreator

**Comment by RubenCasal** [comment]
Cosas para mejorar para las siguientes semanas:
-Añadir el lifestyle/residencia que se tenga en cuenta en la recomendación.
-Añádir ponderación a la hora de puntuar los distintos tipos de requisitos para que pueda elegir el usuario representante.
-Considerar otros apartados para la puntuación.

**Comment by RubenCasal** [comment]
Se ha modificado el código para que se adapte a la nueva estructura de candidato, ya que ahora las experiencias profesionales pasan a formar parte del modelo de base de datos de este

**Comment by RubenCasal** [comment]
Se ha añadido para que los team creator almacen el id del usuario representante a traves del json web token

**Comment by RubenCasal** [comment]
Se ha creado el validador del teamCreator (comprueba que se pasa json web token, que corresponde a un usuario representante, que la query no esta vacia, que no haya ningún perfil completamente vacio)

**Comment by RubenCasal** [comment]
Se han creado todos los validator necesarios:
checkTeamCreatorById (Asegura que el TeamCreator que se pide exista)
checkValidToken (Asegura que el Autorization token sea valido)
checkIsRepresentative (Asegura que el usuario sea un representante)
checkAuthorization (Asegura que el usuario tenga autorización para realizar la acción que se pide)
checkDataCreateTeam (Asegura que la información que se pasa sea correcta)

**Comment by RubenCasal** [comment]
Se ha añadido la funcion de devolver el listado de todos los teamCreator de un usuario representante (getAllTeamCreatorOfRepresentative)

**Comment by RubenCasal** [comment]
El algoritmo de recomendación consta de 4 pasos principales y recibe un input de una lista de "RequestedProfiles", en el que se especifican los requisitos que se pide del candidato(lenguajes,tecnologías, años de experiencia y campo de especialidad) como por ejemplo:
[{
  "languages": ["JavaScript"],
  "technologies": ["React"],
  "yearsOfExperience": 3,
  "field": "Front-end Development"
},
{
  "languages": ["JavaScript"],
  "technologies": ["React","Django"],
  "yearsOfExperience": 3,
  "field": "Front-end Development"
}
]
1) processSkillsRequested
Se procesa la lista de RequestedProfiles, para almacenar en un único objeto todos los requisitos en general. Siguiendo una estructura como la siguiente.
export interface SkillRequested{
    languages: string[];
    technologies: string[];
    yearsOfExperience: number;
    field: string[];
  }
  2)filteredcandidates
  Se filtran todos los candidatos registrados en el sistema que cumplan con almenos uno de los requisitos exigidos, Los candidatos que pasen el filtrado se almacenan con la siguiente estructura para facilitar el procesamiento posterior.
  export interface FilteredCandidates{
    github_username: string;
    languages: string[];
    technologies: string[];
    yearsOfExperience: number;
    field: string[];
  }
  3)selectCandidates
  Con los candidatos filtrados anteriormente, se hace una puntuación de cada uno para cada perfil pedido, sumando un punto por cada requisito que cumplan para dicho perfil exigido. Devuelve los 3 candidatos con mayor puntuación para perfil.
  4)saveTeamCreator
  Se almacena en base de datos la recomendación con la información devuelta de la función anterior y el id del usuario representante.
    const teamCreatorSchema = new Schema({
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    profiles: [{
      profileRequested: profileRequestedSchema, 
      recommendedCandidates: [filteredCandidatesSchema] 
    }]
  });
