### ISSUE TITLE
Integración back y front

### ISSUE THREAD

**Issue by carzarrei** [JaviFdez7/ISPP-G1-Talent#183]
Comprobar la correcta integración entre el código refactorizado de back y front.

- [x] He entendido la issue o comentado las dudas al respecto
- [x] He dado la estimación de tiempo para su realización
- [x] La integración se ha completado y se ha comprobado su correcto funcionamiento
- [x] El trabajo se ha completado y pongo la issue en revisión

**Comment by carzarrei** [comment]
@marizqlav, yo creo que en unas 2 horas entre los 2 lo sacamos bien, dime tu que piensas de cara a la estimación.

**Comment by marizqlav** [comment]
Creo que máximo dos horas

**Comment by motero2k** [comment]
**Se han resuelto los conflictos** de merge

Sin embargo se ha detectado que **existen errores que crashean el backend**.
```bash
Error: Cannot set headers after they are sent to the client
```

Esto ocurre porque se han usado cadenas de ifs en lugar de if-else. Para evitrar el problema podemos añadir un return despues de lanzar la respuesta.
```js
if (token.length > 0) {
      const message = 'User already logged in';
      ApiResponse.sendError(res, [{
        title: 'Bad Request', detail: message}], 400); }])
return; // Añadir esta línea
}
// ...

```

### Nueva subtarea

- [ ] Arreglar los ifs que crashean el backend

**Comment by carzarrei** [comment]
Se han corregido los ifs tanto en user como en history
Se ha arreglado además un error por que se habían cambiado los códigos 409 de conflicto erroneamente por códigos 400 Bad request

**Comment by marizqlav** [comment]
He arreglado los fetch que estaban dando problemas en la integración a frontend 09caf593f29da2411c036f0162a200de7a5adafa
