### ISSUE TITLE
Crear Customer Agreement

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#185]
|**Tiempo estimado** |**2h**|
|-|-|

Será necesario elaborar un documento que recoja todas las cláusulas y acuerdos a los que nos comprometemos con los usuarios. Es importante remarcar las condiciones que aceptan y el uso que se harán de sus datos.

**Comment by Francisco-David** [comment]
Realizándolo en: https://docs.google.com/document/d/18gG_1NukI0zH9QrsaMDgI_uFNl8CTXUo4Is2pSeMjGU/edit#heading=h.3w47vc6c8s4m

Pendiente aun de retocar y la revisión con claudette en https://arxiv.org/abs/1805.01217

**Comment by Francisco-David** [comment]
Terminado en:
https://docs.google.com/document/d/1APmFl6mYxi8IJKhwReHKjHl5NbvXkV3_tu6wxENMgzg/edit#heading=h.v6f92y7saj39

**Comment by IsmaelHerrera2000** [comment]
Customer agreement creado con éxito, en el siguiente sprint se añadirá al código.
