### ISSUE TITLE
notifications-module

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#186]
### Explicación

Se debe implementar el sistema de notificaciones cuando una empresa a revisado el perfill de un candidato. 

**RF9. Notificaciones candidatos:** A los usuarios que utilicen el sistema como candidatos, se les notificará cuando el sistema los recomiende para alguna búsqueda en el proceso de selección. 

Si el usuario tiene activo el plan básico se le mostrará el número de empresas interesadas en su perfil.  (Ejemplo: 2 empresas han visualizado tu perfil)

Si el usuario tiene activo el plan avanzado se le mostrará el nombre de la empresa y permitirá acceder a sus datos de contacto. (Ejemplo: Fujitsu ha visualizado tu perfil)

En backend se guardan todos los datos. Y el frontend controlará que se le muestra al cliente.

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He propuesto mejoras o modificaciones si fuera necesario
- [x] He creado el nuevo modulo
- [x] He realizado todos los endpoints necesarios siguiendo los principios REST
- [x] He creado el documento de oas (swagger)
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by andresdominguezruiz** [comment]
**Pregunta sobre issue:** ¿Hay límite de notificaciones?

**Comment by andresdominguezruiz** [comment]
**Tiempo estimado:** 3 horas

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Modelo creado y métodos preparados

**Trabajo restante:**

- Hacer métodos funcionales
- Revisar funcionalidades

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Solucionar bug de la creación automática de notificaciones
- Rutas de controlador: actualizar mensaje de notificación, visualizar buzón, borrar notificación y ver notificación.

**Comment by motero2k** [comment]
> **Pregunta sobre issue:** ¿Hay límite de notificaciones?

Se respondió que no. Al menos en esta iteración

**Comment by motero2k** [comment]
La tarea esta revisada y aprobada.
