### ISSUE TITLE
experiences-to-user

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#187]
### Explicación

Se debe mantener los endpoints de professional experience. Sin embargo, para el algoritmo de creacion de equipos es necesario que se guarde dentro de la tabla de users con un atributo professionalExperience de tipo array.
### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He propuesto mejoras o modificaciones si fuera necesario
- [x] He mantenido intacto el documento de oas (swagger)
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by RubenCasal** [comment]
Esta issue se finalizará en menos de 1 hora

**Comment by RubenCasal** [comment]
se han hecho los cambios, para añadir las experiencias profesionales al modelo de usuario, y los cambios necesarias, para que los validadores funcionasen
