### ISSUE TITLE
subscription-plans

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#188]
### Explicación

Se debe implementar el sistema de planes de suscripciones. Al menos que se guarden como objeto dentro de  un campo `plan` en user. Se puede proponer mejoras de los requisitos como añadir la fecha del ultimo pago.

- RF18. Plan de suscripción representantes: Los usuarios representantes con 3 tipos de planes, plan básico, plan avanzado y plan personalizado, Cada plan personalizado representará un cambio en las funcionalidades de la aplicación, el cual será especificado en los requisitos .

- RF8. Plan de suscripción: Los usuarios  candidatos  al acceder a su perfil e irse a la zona de “Mi plan” podrán optar por mejorar su plan actual al avanzado, para mejorar y desbloquear funcionalidades adicionales de la aplicación, especificadas en los requisitos RF9, RF10 y RN12  . Para los usuarios candidatos únicamente habrá dos planes, el plan básico que es gratuito y el avanzado con un precio de 10€.

- Permitir suscribirse a los planes o cambiarse de plan

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] He buscado en internet como se suelen implementar estos sistemas
- [x] He propuesto mejoras o modificaciones si fuera necesario
- [x] He creado el nuevo modulo, aunque el servicio se conecte a la tabla de users
- [x] He propuesto los endpoints necesarios
- [x] He realizado todos los endpoints necesarios siguiendo los principios REST
- [x] He creado el documento de oas (swagger)
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by carzarrei** [comment]
@motero2k El trabajo a realizar entiendo que es sin contar el tema de precios y tal, aunque el objeto de los planes tenga dentro un campo precio, pero para cambiar de planes no hay que implementar el pago aún.

La tarea es grande, por lo que creo que me llevará al menos 3 horas y hasta 4, llegando así a las 7 horas estipuladas para esta semana.

**Comment by carzarrei** [comment]
El plan para empezar a implementar las suscripciones es guardarlas como objetos a parte en la base de datos con los siguientes atributos:

**Comment by carzarrei** [comment]
Se ha creado ell módulo, definido los endpoints principales y cambiado los métodos en controladores y servicios para adecuarse a las rutas. Los servicios aún no están implementados. Es una primera versión prototipo

**Comment by motero2k** [comment]
Con eso es suficiente para una promera version. Dependemos de lo que nos requiera frontend

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Revisar métodos
- Primera versión de swagger funcional

**Trabajo restante:**

- Middlewares
- Validaciones de los límites de cada tipo de subscripción

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Middlewares a la hora de actualizar una subscripción de un usuario y de verlo

**Trabajo restante:**

- Validaciones de los límites de cada tipo de subscripción

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Validaciones de los límites de cada tipo de subscripción
