### ISSUE TITLE
Primera version de vista de búsqueda

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#190]
| Duración | 4.5 horas |
|----------|--------|

Realizar una primera versión de vista de búsqueda basándose en los requisitos y mockups

**Comment by albdomrui20** [comment]
*Trabajo realizado:*
- Vista de equipo de candidatos de un representante
- Componente DataTableVertical y DropDown
- Añadido vista de equipos a navbar de representante
*Trabajo por realizar:*
- Vista de formulario de buscador
- Añadir botones de eliminar candidato de equipo
- Vista de resultado de busqueda

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Vista de formulario de buscador
- Añadir botones de eliminar candidato de equipo

**Trabajo por realizar:**
- Vista de resultado de busqueda

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Vista de resultado de búsqueda
- Arreglado texto de botón y mejorado formulario de búsqueda
- Añadido imágenes de perfil en los candidatos de búsqueda (un placeholder para sustituir por los datos de verdad)

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Modificado formulario para que languages y technologies sean multiple seleccion (technologies en base a el tipo de tecnologia)
- Refactorizado nombres incorrectos de clases y constantes

**Trabajo por realizar:**
- Cambiar el formulario para que acepte varios filtros de candidato a la vez
- Mejorar el aspecto de los selects (de momento son simples pues estoy teniendo problemas al intentar implementar librerias)

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Añadido la posibilidad de varios candidatos por búsqueda

**Comment by dangalmar** [comment]
Revisado
