### ISSUE TITLE
Actualización del documento de costes

### ISSUE THREAD

**Issue by JaviFdez7** [JaviFdez7/ISPP-G1-Talent#192]
| Duración | 2 horas y 30 minutos|
|----------|--------|

- [x] A poder ser, recalcular en el documento las estimaciones de los costes(realista, optimista y pesimista), ya que no deben ser lineales porque fluctúan según el número de usuarios.
- [x] Añadir un PERT en las estimaciones pesimistas, optimistas y realistas de los costes.
- [x] Las estimación a futuro del presupuesto (budget) no puede ser lineal, debe hacer fluctuar los datos.
- [x] Estimar el número de peticiones que se podrían hacer en total y decir cuanto nos costaría con la responsabilidad de usar la API key de github de nuestra organización.
- [x] Hacer un análisis de la capacidad de las peticiones, para estimar el n° de peticiones óptimo para los clientes en los diferentes planes de suscripción.
- [x] Análisis económico de las peticiones que harán los clientes.

Tener en cuenta lo siguiente:

Poner la clave de github (API) al cliente es arriesgado si la empresa es la que tiene que hacer los análisis. Sobre todo si el cliente ya usa su api para otras cosas, el requisito de uso es demasiado alto, no es profesional.

**Comment by FJMonteroInformatica** [comment]
Se han realizado todas las modificaciones.

**Comment by motero2k** [comment]
Genial. Veamos que opina el equipo de presentaciones. PD: Ya se revisó el cambio de calculos por usar la api de github GQL en lugar de la Rest. Cierro la issue aunque puede que se hagan ligeros retoques.
