### ISSUE TITLE
A bug in github username

### ISSUE THREAD

**Issue by marizqlav** [JaviFdez7/ISPP-G1-Talent#200]
## Mensaje
El problema como se puede ver en pantalla es que cuando se pone en el github username, archivo RegisterCandidate.jsx, un nombre raro te sale por pantalla ese mensaje, el cual se muestra porque :
if (error.response.status === 409 || error.response.status === 400) { // set the status code properly
        setErrors(error.response.data);
        return;
{errors && errors.errors && errors.errors[0] && errors.errors[0].detail && (
          <p className="text-red-500">{errors.errors[0].detail}</p>
        )}
 Se además que por la posición que sale tiene que estar ahí y además es rojo.
![bug 1](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/113362030/bb760a23-3c50-4068-b2a8-5592683a0adc)
![bug 2](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/113362030/cc2f3535-7dfc-4cb7-a504-a2d82d340981)

**Comment by motero2k** [comment]
El error se podía resolver desde las peticiones del frontend. Mario comenta que está solucionado. Marco la issue como cerrada.
