### ISSUE TITLE
Arreglar errores del historial de análisis

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#203]
| Duración | 1.25 horas |
|----------|--------|

**Trabajo a realizar:**

- [x] Actualizado reactivo de botón de favoritos.
- [x] Actualizado reactivo de botón de borrar historial.
- [x] Correcta inicialización del icono de favoritos.

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Eliminada la repetición de historiales.
- Actualización de fecha de historiales implementada.

**Trabajo por realizar:**

- Reactividad de favoritos y delete.

Hash del commit: 7fbe0fc81883c0b5ce2c0222a110ac8696e2e4d4

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Mejora de reactividad.
- Mejora de muestra de errores al borrar historial.

Finalmente, no se considera útil implementar reactividad en el icono de favoritos.

Hash del commit: dc616896b6f9bba3f99b429a5c263d32e7d2fae9

**Comment by carlos-bermejo** [comment]
Tiempo invertido: 1 hora y 8 minutos.

**Comment by dangalmar** [comment]
Todo bien
