### ISSUE TITLE
Adaptar vistas para que puedan verse en móvil

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#204]
| Duración | 3.5 horas |
|----------|--------|

Adaptar todas las vistas a móvil y comprobarlo mediante diferentes tamaños de pantalla

**Comment by alemerpal** [comment]
He adaptado las vistas para que se vean bien en pantallas de movil. Faltan las vistas de subscripción, información y settings que de todas formas habría que rediseñar, por lo que recomiendo hacerlo en otro issue. También he adaptado algunos estilos en analisis en navbar.
[ec8c62d](https://github.com/JaviFdez7/ISPP-G1-Talent/commit/ec8c62d8721e03cc576f3786cb6f6b7c33d7ff59)

**Comment by dangalmar** [comment]
Revisado y aceptado
