### ISSUE TITLE
Implementar funcionalidad de experiencia profesional

### ISSUE THREAD

**Issue by marizqlav** [JaviFdez7/ISPP-G1-Talent#206]
| Duración | 3.5 horas |
|----------|--------|

Integrar los endpoints de experiencia profesional en candidato

**Comment by marizqlav** [comment]
He terminado de implementar funcionalidad de experiencia profesional, donde en el perfil de candidato al final aparece esta  sección y sino tienes creado uno te aparecerá en blanco y si tienes uno te aparecerán los datos de este. Al lado esta el botón de Detail, para ver sus detalles y pulsándolo te lleva a la vista de sus detalles donde ademas hay otro botón para editar esa experiencia de usuario. Solo podrás crear una y si intentas creas mas de una te salta un pop-up. No he hecho el eliminar porque no se si se puede o seria necesario.33f36f789c4ee3cea049d9d7d895ff3f7b4cb5c9
Cabe resaltar el error que he comunicado a backend, como es que solo te permita crear una experiencia de usuario. Además de que el ProfessionalExperienceMiddleware devuelve Strings en lugar de JSON, aunque quizás los errores no se vean por pantalla debido a los validate.

**Comment by alemerpal** [comment]
He *terminado* de implementar la funcionalidad de experiencia profesional, a falta de mejorar el estilo visual

**Comment by dangalmar** [comment]
Se ha revisado y se dejaran los arreglos visuales para otra issue
