### ISSUE TITLE
Acciones de consolidación W6 y W7

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#217]
| Duración | 30 minutos |
|----------|--------|

Será necesario añadir las acciones de consolidación sobre lo que hemos hecho en las semanas 6 y 7.

**Comment by Francisco-David** [comment]
Realizada sobre el documento:
https://docs.google.com/document/d/1-JdmIlDlgtamA9A6RrK8hMSK3KW3ZWJ4nYqbhNbHEMg/edit

**Comment by IsmaelHerrera2000** [comment]
El documento es correcto.
