### ISSUE TITLE
Cambiar la validación del correo en el registro de usuario

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#221]
| Duración | 1.25 hora |
|----------|--------|

Es necesario realizar una comprobación de la existencia del correo electrónico que se introduce en el registro de usuarios.

TAREAS A REALIZAR:

- [x] Realizar una primera comprobación de que el campo introducido es un correo (expresión regular)
- [x] Realizar la comprobación de existencia de correo mediante una API externa

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Implementación manual de validación mediante Verifalia.
- Arreglo de fallos en registro.

Hash del commit: 00452e2871d0056e44e90e0f49bdad319f1c4861
Tiempo invertido: 2h 30min

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Añadida implementación para candidatos.
- Añadida variable de entorno para activar/desactivar validación de correo.

Hash del commit: 03564b2429990fda1cd4d782d2385ec1b9e882e7
Tiempo invertido: 30min

**Comment by dangalmar** [comment]
Revisado y aceptado
