### ISSUE TITLE
Finalizar feature de work experience

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#222]
| Duración | 2.5 horas |
|----------|--------|

Se han detectado problemas en la creacion de la entidad asi como incoherencias en el formulario de creacion.

TAREAS A REALIZAR:

- [x] Corregir el formulario para que sea coherente (Que pida fecha final, que la fecha final este despues de la fecha inicial, etc)
- [x] Solucionar problema con creacion de entidad en la que se desconecta el backend (hablar con backend si es necesario)
- [x] Mejorar vista 
- [x] Permitir que se pueda borrar work experience

**Comment by marizqlav** [comment]
He tocado tanto CandidateProfessionalExperienceEdit como CandidateProfessionalExperienceCreate para que se pueda crear un experiencia profesional modificando la fecha final para que esta sea o el mismo dia que la de inicio, posterior a esta o como muy tarde la fecha de su creacion. Además ya se pueden crear tantas experiencias profesionales como se quieran.

**Comment by marizqlav** [comment]
He terminado la funcinalidad de delete a falta de mejorar el Model.a1f47d06eba097789fa0d69752a72e7e001a328e

**Comment by dangalmar** [comment]
Revisado y aceptado
