### ISSUE TITLE
Integrar con backend la busqueda de equipos

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#224]
| Duración | 2 horas |
|----------|--------|

Una vez hecha la vista se busca integrarse con backend asi como realizar alguna mejora de la vista si es necesario.

TAREAS A REALIZAR:

- [x] Realizar integracion con backend para permitir crear equipos (hablar con Rubén)
- [x] Adaptar la vista si es necesario una vez se ha realizado la integración

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Se ha realizado la conexión con backend.
- Se ha mejorado las vistas con respecto a la primera versión

**Trabajo por realizar:**
- La versión actual del backend da problemas con los análisis (a los que llama el team-creator). Volver a integrar backend una vez estén solucionados los problemas.

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Mergeo con backend arreglado.

**Comment by dangalmar** [comment]
Revisado
