### ISSUE TITLE
codacy fixes in backend

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#226]
### Descripcción

Se deben arreglar la mayor cantidad de issues de codacy posibles. No se trata de arreglarlo todo, sino de reducir deuda técnica.
https://app.codacy.com/gh/JaviFdez7/ISPP-G1-Talent/dashboard?branch=backend
### Tareas
- Revisar codacy
- Arreglar issues en una rama que nace de backend

|Estimacion de tiempo|1h max|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Resolver Error prones
- Buscar problemas críticos y severos

**Trabajo restante:**

- Eliminar code smells y malas prácticas

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Gran parte de los code smells solventados, dejando un 3% de issues.

**Comment by andresdominguezruiz** [comment]
![Image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72501425/35493c84-6bd8-43af-a07d-12ba4ed0de32)

Estado actual
