### ISSUE TITLE
Informe de feedback de las presentaciones del 19/03/2024

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#230]
|**Tiempo estimado** |**1h**|
|-|-|

Recoger todo el feedback recibido durante la clase en un documento.

**Comment by Moffinguer** [comment]
https://docs.google.com/spreadsheets/d/1vjDdajdJHCcg5G8w3haS24YhxKHV0oWbAG94f7oykro/edit#gid=1836350107

**Comment by IsmaelHerrera2000** [comment]
El feedback se ha recogido correctamente.
