### ISSUE TITLE
Separar update de usuarios

### ISSUE THREAD

**Issue by carzarrei** [JaviFdez7/ISPP-G1-Talent#231]
### Descripción

Se debe implementar un cambio al update de usuarios, de modo que quede separado en 3:
- Cambio de foto de perfil
- Cambio de contraseña
- Cambio del resto de datos editables

### Tareas
- Crear los endpoints necesarios para los nuevos métodos
- Crear los nuevos métodos
- Actualizar Validaciones de ususario
- Actualizar documentación

|Estimacion de tiempo|-|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by FJMonteroInformatica** [comment]
Estimo que la tarea me llevará alrededor de una hora.

**Comment by FJMonteroInformatica** [comment]
La edición de la foto de perfil y de la contraseña se han separado de la edición del resto de campos y se han actualizado los validadores en consecuencia. Únicamente falta actualizar Swagger para documentar los nuevos métodos.

**Comment by FJMonteroInformatica** [comment]
La tarea ha sido completada.

**Comment by motero2k** [comment]
Esta tarea se cierra y se realizan los nuevos cambios de requisitos en otra tarea. Buen trabajo!
