### ISSUE TITLE
Despliegue del S2

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#235]
|**Tiempo estimado** |**1h**|
|-|-|

Será necesario hacer el despliegue de la nueva versión de IT-Talent para la sesión de evaluación. Es importante que esté desplegado en una instancia a parte del S1.

**Comment by Moffinguer** [comment]
https://frontend-s2-dot-italent-415216.oa.r.appspot.com/
https://backend-s2-dot-italent-415216.oa.r.appspot.com/

**Comment by IsmaelHerrera2000** [comment]
Desplegado con éxito.
