### ISSUE TITLE
Integrar la funcionalidad de notificaciones

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#238]
| Duración | 2 horas |
|----------|--------|

TAREAS A REALIZAR:

- [x] Crear la vista de notificaciones
- [x] Integrarse con backend (hablar con Andrés)
- [x] Comprobar correcto funcionamiento (solo una notificacion por representante que lo ve, que la lista de notificaciones este ordenada por la más reciente, etc.)

**Comment by dangalmar** [comment]
Se han detectado fallos en la comprobacion de la repeticion de usuario e email.

**Comment by alemerpal** [comment]
Arreglado, sumaría una hora a la estimación

**Comment by dangalmar** [comment]
Revisado y completo
