### ISSUE TITLE
Pasarela de Pago

### ISSUE THREAD

**Issue by Moffinguer** [JaviFdez7/ISPP-G1-Talent#240]
Montar una pasarela de pago sencilla con Stripe.
Tomar 1 de 2 decisiones:
- La app solo podrá usarse cuando un plan haya sido escogido, o si no se te ha acabado el mes
- La app tendrá características bloqueadas hasta que te subscribas a un plan, o mientras no se haya acabado el mes

**Comment by Moffinguer** [comment]
@motero2k @dangalmar Deben de decidir una decisión de las 2, al no tener en la app desplegada en la nube un sistema de sesiones, de momento

**Comment by dangalmar** [comment]
En este caso tenemos que la decision 1 casa mejor con el rol de representante, mientras que la 2 casa mejor con el candidato.

Lo lógico sería implementar la decisión 1 para representante debido a que hasta el plan básico vale dinero, mientras que el plan básico del candidato es gratis por lo que sería absurdo impedir el uso de la aplicación. 

Entiendo que como lo has puesto solo se puede elegir una de las dos pero explicame el porque una excluye a la otra porque no lo veo.

**Comment by Moffinguer** [comment]
> En este caso tenemos que la decision 1 casa mejor con el rol de representante, mientras que la 2 casa mejor con el candidato.
> 
> Lo lógico sería implementar la decisión 1 para representante debido a que hasta el plan básico vale dinero, mientras que el plan básico del candidato es gratis por lo que sería absurdo impedir el uso de la aplicación.
> 
> Entiendo que como lo has puesto solo se puede elegir una de las dos pero explicame el porque una excluye a la otra porque no lo veo.

Si se escoge una solución u otra afecta a la forma en la que se le avisa al cliente:
- Si se toma la solución 1 te cercioras de que el cliente deba de pagar para acceder a datos particulares( como mensajes, o datos personales, o estadisticas de su perfil, características que no se ven afectadas por la propia aplicación, sino que son intrinsecas), cosas que sin usar la app per se, podría usar. Es una forma de evitar morosos.

- La segunda solución permite al usuario usar ciertas funcionalidades básicas, pero no usar la aplicación per se. Si queremos obtar por un sistema más laxo y no tan estricto, sería bastante util. Y concuerda bien con un sistema de perfiles distintos que pueden acceder a ciertos recursos, que otros no.

**Comment by motero2k** [comment]
A ver la app solo puede usarse registrado y con un plan. Ahora bien el plan que se le asigna a un candidato por defecto es el básico y es gratis. Este plan restringe ciertas funcionalidades. Así es como se está trabajando desde el backend.

**Comment by Moffinguer** [comment]
> A ver la app solo puede usarse registrado y con un plan. Ahora bien el plan que se le asigna a un candidato por defecto es el básico y es gratis. Este plan restringe ciertas funcionalidades. Así es como se está trabajando desde el backend.

Pero cuando entras en la app, a no ser que seas el candidato, deberás de decidir como se va a comportar la aplicación hasta que se subscriba por primera vez.
Porque cuando te registras no lo haces en ningún momento. Por lo tanto se debe de decidir como manejar esto, algo que afecta a los permisos de la aplicación tanto en backend como en frontend

**Comment by dangalmar** [comment]
Pues la mejor sería la 1. No obstante, como dice @motero2k para el candidato con registrarse obtendría el plan básico con opción de cambiar a premium.

**Comment by Moffinguer** [comment]
Vale pues entonces con eso queda aclarado.
Estoy averiguando una forma para que cuando se haga el cobro con ese formulario de Stripe, vosotros verifiqueis si se ha hecho o no el cobro.

Para eso se me está ocurriendo 2 formas, intento buscar la que menos codigo haya que hacer, porque montar un formulario de pago, aunque sea simple, requiere después manejar muchas casuisticas.
- La más sencilla de todas es tener un endpoint que llamamos para consultar los pagos de stripe realizados en el ultimo mes. Si el nombre del usuario no se encuentra ahi, entonces deberá de volver a pagar. Este endpoint, aunque se le llame desde el frontend DEBERÁ, de arrancar periodicamente desde el backend para cambiar el tipo de subscripción que tenga cada uno.

- La otra sería montar un formulario propio, y eso requiere una tabla nueva en la base de datos + codigo, tanto en backend como en frontend, para controlar los pagos.

Además hay que verificar que el usuario y correo existan de antemano: muy sencillo de verificar si hacemos lo siguiente:
https://docs.stripe.com/payment-links/customize#customize-checkout-with-url-parameters

Aqui explica como añadir parametros custom. Se verifica de antemano, por nuestra aplicación que esos 2 datos los poseemos nosotros. Si alguien hace un pago y no pasa por ahi, es problema suyo, nosotros ganamos dinero y ellos se quedan sin subscripción.

Usando un webhook, podemos comprobar que un pago se ha realizado satisfactoriamente a ese usuario:
https://docs.stripe.com/webhooks

Hay ejemplos en node

**Comment by motero2k** [comment]
Yo pensaba ponerle al user un payent con fecha fecha de coaducidad y una referencia al id de stripe

**Comment by Moffinguer** [comment]
Solución final:
- Añadir un campo en la base de datos relacionado al usuario de stripe. Campo opcional, es una cadena
- En la vista de planes de subcripción cada plan llevará a la pestaña correspondiente al plan de subscripción
- Si es la primera vez que se suscribe con el plan basico de Representante, no redirigir a la vista de la pasarela de pago, sino si.
- Antes de redirigir a la vista de la pasarela de pago se deben de hacer 3 cosas: 
     1. Debemos de obtener el username y el correo del usuario
     2. Debemos de verificar que esa combinacion de username y correo existe en el sistema
     3.  <enlace-plantilla>?prefilled_email=<email> | Abrir en una nueva pestaña
     4. Ejecutar en la vista una llamada al backend, comprobando si el plan del usuario está relleno, si ya es de alguno de los tipos admitidos.
     
- Por el lado de backend deberá de hacer lo siguiente:
     1. Ejecutar un proceso por un tiempo máximo de 24 horas
     2. Este proceso constará de 2 partes.
          a. Acceder a la lista de Clientes de Stripe, y comprobar que existe alguno con el correo de nuestro usuario.
          b. Si se llega a encontrar entonces obtener el ultimo PaymentIntent de ese usuario
          c. Si la fecha de creación, "created", fue hace más de un mes o el "status" no es "succeeded", entonces se deberá seguir preguntando por el ultimo PaymentIntent
          d. Si el status llega a ser "canceled", o han pasado 24 horas, cerrar el proceso.
          f. Si ha terminado satisfactoriamente, añadir el campo del id del cliente de Stripe, al usuario en la base de datos, y modificar el modo de subscripción.
          
          
@dangalmar @motero2k Este es el proceso entero. Debo de escribirlo yo todo? Ya que estoy tocando en codigo tanto de frontend como de backend y estais haciendo cosas, yo no tengo tanto conocimiento del codigo como vosotros ahora mismo.

**Comment by dangalmar** [comment]
En cuanto mergee los dos pull request para frontend podrás comenzar. Por cierto en el punto 3 sería plan básico de candidato no representante.

**Comment by Moffinguer** [comment]
> En cuanto mergee los dos pull request para frontend podrás comenzar. Por cierto en el punto 3 sería plan básico de candidato no representante.

Gracias, corregido!

**Comment by Moffinguer** [comment]
@dangalmar @motero2k Voy a necesitar a una persona tanto de backend como de frontend a las que les pueda preguntar y solicitar ayuda para montar algunas cosas, por la falta de conocimiento de la estructura interna del codigo y agilizar las cosas.

Al estar el flujo claro, solo tendria dudas técnicas. Asignad a 1 persona cada uno como apoyo

**Comment by motero2k** [comment]
Del backend puedes contactar con @andresdominguezruiz que trabaja en suscripciones y @RubenCasal para los analisis

**Comment by Moffinguer** [comment]
Dejado para el S3

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Plan custom convertido en "mock".
- Creado componente _PricingTable.jsx_ funcional.
- Actualizado **feedback de usuarios piloto** (icono de popular ahora realista).

**Trabajo por realizar:**

- Implementación final con Stripe y endpoints del backend.
- Pruebas manuales.
- Comprobación de credenciales del usuario (contraseña y username).
- Discutir escenarios de uso: plan gratuito, downgrades de plan.

Tiempo invertido: 1h 20min
Hash del commit: 6a7e7ffebe6143bbdd3bf0a5cf9b7036e0359988

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Implementación funcional por parte del frontend (falta el backend).

**Trabajo por realizar:**

- Downgrades de plan.
- Registro de representante (necesita escoger un plan desde el principio).
- Plan gratuito (no necesita página de pago).
- Pruebas manuales (necesita finalizar backend).

Tiempo invertido: 2h 14min
Hash del commit: b4d6fdc50565386d3e07f7885d693d38ba80843a

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- _Rebase_ con develop y rama de feature.
- Implementación funcional backend y frontend.
- Downgrades de plan.
- Configurado plan gratuito (sin datos de pago) -> Cambiado en frontend y backend.
- Fix registro de representante.
- Pruebas manuales de toda la aplicación (para asegurar que no haya problemas de _rebasing_).
- Pruebas manuales de pasarela de pago.

**Trabajo por realizar:**

- Comprobar integración con privatización de rutas.

Tiempo invertido (en **total**): 13h
Hash del commit: f829eb8203c5a2372fb7d943ff88c568bbb3bd8a

**Comment by dangalmar** [comment]
Ya se ha revisado y se mergea a develop. Gran trabajo !!!
