### ISSUE TITLE
fix-broken-functionality

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#241]
### Descripcción
Detectado por @albdomrui20  y debuggeado junto a @motero2k.

Se debe arreglar la funcionalidad de crear un analisis que se ha roto tras arreglar issues de codacy.

### Tareas
- Desacer los cambios de codacy que rompen la funcionalidad del backend
- Revisar TODA la funcionalidad del backend en swagger antes de hacer una PR

|Estimacion de tiempo|30 min|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by albdomrui20** [comment]
*Capturas del error:*

- Input: 

![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72875238/50439875-0692-4805-9e4c-2793308fc199)

- Resultado: 
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72875238/ed1fbadf-c459-4f82-8d11-55d3130e3f6a)

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**
Problema solucionado

**Comment by motero2k** [comment]
@albdomrui20  por favor prueba que te funcione junto a tu rama de front.
