### ISSUE TITLE
Estándar de respuesta en ProfessionalExperience

### ISSUE THREAD

**Issue by FJMonteroInformatica** [JaviFdez7/ISPP-G1-Talent#247]
### Descripción

Detectado por @marizqlav. Las experiencias profesionales deben seguir el estándar de respuesta JSON:API. Para ello, se deberá utilizar la clase ApiResponse. Se tienen múltiples ejemplos de ello en todos los módulos de la aplicación, además de un documento en el que se explica cómo utilizar esta clase.

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones (si fuera necesario).
- [x] He realizado la tarea y la pongo en revisión.
- [ ] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by motero2k** [comment]
cual es el estado de esto @FJMonteroInformatica ?

**Comment by FJMonteroInformatica** [comment]
> cual es el estado de esto [@FJMonteroInformatica](https://github.com/FJMonteroInformatica) ?

Está en el mismo estado, me pondré con ello. No estimo tardar más de 15 minutos.

**Comment by FJMonteroInformatica** [comment]
Mirando la última versión de la rama develop, parece ser que las respuestas siguen el estándar JSON:API. Creo que hubo una confusión al trabajar con una versión desactualizada de la aplicación. Pongo la tarea en revisión, para que alguien más lo confirme.
