### ISSUE TITLE
Informar sobre expiracion de token y modal de confirmacion de borrado

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#249]
| Duración | 1.30 horas |
|----------|--------|

TAREAS A REALIZAR

- [x] Informar al usuario de la expiracion del token
- [x] Solucionar el mensaje de error que sale al borrar un analisis en el historial
- [x] Poner un modal de confirmación al borrar un analisis en el historial

**Comment by marizqlav** [comment]
He creado un componente pop up para informar al usuario de la expiración del token, he solucionado el mensaje de error que sale al borrar un análisis en el historial y he puesto un modal de confirmación al borrar un análisis en el historial.
e0658bb2b35dd527b74f95c776a3c83ba8e3cd16

**Comment by dangalmar** [comment]
Errores encontrados:

- Cuando un analisis esta en favoritos, no me permite borrarlo

**Comment by marizqlav** [comment]
Ya lo he arreglado creando un nuevo componente para que no aparezcan esas opciones en el perfil del representante.
ba160cf97c2b6edc0f5064017b56498efab8ec53

**Comment by dangalmar** [comment]
Revisado
