### ISSUE TITLE
Actualizar TCO a partir de la validación del correo

### ISSUE THREAD

**Issue by andresdominguezruiz** [JaviFdez7/ISPP-G1-Talent#269]
**Descripción:**
Debido a la nueva información de la validación del correo, es necesario actualizar el TCO para que cumpla con lo necesario.
**Tiempo estimado:** 1h y 30 minutos

- [x] He entendido la tarea y he comunicado cualquiera de mis dudas
- [x] He proporcionado mejoras e ideas a la tarea y las he comunicado al grupo
- [x] He acabado la tarea y la he puesto como PR

**Comment by FJMonteroInformatica** [comment]
Se ha actualizado el documento de costes en consecuencia.

**Comment by motero2k** [comment]
Revisado y cerrado
