### ISSUE TITLE
Rendimiento individual final de Sprint 2

### ISSUE THREAD

**Issue by JaviFdez7** [JaviFdez7/ISPP-G1-Talent#273]
### Descripcción
Es necesario realizar el rendimiento individual de la semana 8 y además computar la media de rendimiento durante las 3 semanas del sprint 2 para cada miembro. Es necesario tener en cuenta el feedback sobre eliminar el número de hora como métrica y añadir que los miembros de los subequipos se puedan puntuar

|Estimacion de tiempo|1 hora|
|-|-|

**Comment by JaviFdez7** [comment]
Se ha empezado a trabajar en la tarea en este excel: https://docs.google.com/spreadsheets/d/1QRk0et-sujj0QRomhRvNnbRG_8q87Eatm1FuGcMnCxg/edit#gid=1341646353

**Comment by JaviFdez7** [comment]
Comunicado para que se puntuen los miembros entre si

![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/100673872/cb6c6771-1ccb-4aa4-b662-46f83a61940f)

**Comment by JaviFdez7** [comment]
Unicamente quedan que se rellene completo: 
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/100673872/e35f64cb-dd33-4184-a453-cdff49eb7fc1)

**Comment by IsmaelHerrera2000** [comment]
El rendimiento individual se mide correctamente.
