### ISSUE TITLE
Realizar la visualización de los datos de análisis de candidato en su perfil

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#282]
TAREAS A REALIZAR

- [x] Visualizar los datos del analisis de un candidato
- [x] Mejorar la visualizacion de los datos y estilos ( el correo no se ve al completo y los datos de analisis)

**Comment by marizqlav** [comment]
He terminado la tarea y se puede ver desde el perfil 3 tablas con datos del analisis del Github del candidato.

**Comment by dangalmar** [comment]
Todo correcto
