### ISSUE TITLE
Realizar pruebas de interfaz de los casos de uso de la aplicación

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#284]
| Duración | 4 horas |
|----------|--------|

TAREAS A REALIZAR

- [ ]  Realizar pruebas de interfaz de los casos de usos core de la aplicación (mirar documento de requisitos)

- [ ]  Exportar los test (codigo o ficheros) y ponerlos en una carpeta llamada test dentro de la carpeta app para que puedan ser ejecutados

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Test básico para: CU1, CU2, CU3
- Instalación de dependencias de 'selenium-webdriver'

**Trabajo por realizar:**

- Test básico para: CU4, CU5
- Creación de un JS que agrupe todos los casos de uso (CU) en un test y se aseguren de la correcta inicialización y finalización de los tests.

Hash del commit: 8011cca652fbe536a54621829c2b0ac258b91437

**Comment by carlos-bermejo** [comment]
Aún **no todos los tests funcionan correctamente** porque necesitan inicializarse correctamente en un Script de JS. Sin embargo, los test de registro se pueden probar siempre y cuando se borre manualmente la BBDD local.

Para ejecutar un test:

- Ejecutar _node app/test/NombreDelTest.js_
- Observar resultados en consola

Para debuggear un test:

- Ejecutar _node --inspect-brk app/test/NombreDelTest.js_
- Abrir Chrome
- Introducir _chrome://inspect/_ en la barra de navegación
- Hacer clic en _Open dedicated DevTools for Node_
- Debuggear el programa de test

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Arreglados los tests que fallaban.
- Añadido TestUseCases.js para ejecutar todos los tests simultáneamente.

Hash del commit: 4a3d4e777d0f9181378917eb28a523423626e9e2

**Comment by carlos-bermejo** [comment]
Actualmente para ejecutar un test hay que utilizar obligatoriamente _node app/test/TetsUseCases.js_.

**Tareas por realizar:**

- Tests de los casos de uso CU4 y CU5.
- Base de datos de test.

**Comment by carlos-bermejo** [comment]
He añadido los tests de katalon como un archivo importable en Katalon Recorder.

**Comment by carlos-bermejo** [comment]
Están habiendo problemas para automatizar los tests con Node, así que por ahora solo se pasarán las test suites de Katalon

**Comment by dangalmar** [comment]
Vamos a dejar solo los test de Katalon. Mergeo
