### ISSUE TITLE
Poder ver los análisis de los candidatos en las búsquedas

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#285]
TAREAS A REALIZAR:

- [x]  Tras realizar una búsqueda permitir que un representante pueda ver los análsis de los candidatos

- [x]  Mejorar los estilos de la vista de equipos (dejar espacio para la foto de perfil de candidato)

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Se ha añadido un botón en los resultados de búsqueda que:
   - Si el análisis ya se ha hecho te redirige al análisis
   - Si no, te redirige al formulario de análisis
- Se ha mejorado la vista para ordenador

**Trabajo por realizar:**
- Dejar espacio para la foto de perfil del candidato

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Se añadido fotos de usuario de Github a los candidatos encontrados en las búsquedas

**Comment by dangalmar** [comment]
Faltan las siguientes tareas:

- [ ] Poner los 3 candidatos buscados en hilera horizontal
- [ ] Cambiar "search result" por "search candidate"

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Se ha puesto los 3 candidates en una sola fila. Commit: 4e12bda525e0748def5448ea1d7177c8e673e9bd 
- Se ha cambiado search result por Searched Candidate. Commit: ff87a37f7becb2cd4a66148d2a954e09063af0ee
- Se han adaptado las vistas de SearchTeam para mobile. Commit: c4793dffd41b70c76ff11cf3db5e395e6b8a5e80

**Comment by dangalmar** [comment]
Todo revisasado y correcto
