### ISSUE TITLE
user password changes

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#289]
### Descripcción
El cambio de contraseña de un usuario debe cumplir:

### Tareas
- La contraseña no puede ser la misma que la actual
- Se debe indicar la contraseña actual para cambiar la contraseña.

|Estimacion de tiempo|1h|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by FJMonteroInformatica** [comment]
Se ha completado la tarea y actualizado Swagger en consecuencia.
