### ISSUE TITLE
backend try catch

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#290]
### Descripcción

Todo endpoint del backend. (TODOS) deben tener un controller en el que se haga: (pseudocodigo)
```js
controller(){
try{
return ApiResponse(serviceCall())
}catch (e){
return ApiResponse(error)
}
}
```
Repito es pseudocodigo. No debe cambiar la estructura original mas alla de añadir try catches.
### Tareas
- Poner todos los trycatch necesarios

|Estimacion de tiempo|1h30m|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by andresdominguezruiz** [comment]
**Tiempo estimado:** 1h

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Poner en formato correcto todos los métodos de los controladores
