### ISSUE TITLE
Testing plan

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#294]
### Descripcción

Se debe realizar el plan de testing para el project launch.

### Tareas
- Poner un enlace al MD de plan te testing
- Crear el plan

|Estimacion de tiempo|-|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by RubenCasal** [comment]
Plan de testing: https://docs.google.com/document/d/1KwNqkduOO9UvkFdU3a8arhvljcG3EoJKw9TpD_Gn7E0/edit

**Comment by motero2k** [comment]
El documento se ha revisado en la reunion. Debemos pasarlo a MD y ponerlo en la sección de documentacion @andresdominguezruiz
