### ISSUE TITLE
Actualizar Storyboard de Candidato

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#298]
|**Tiempo estimado** |**1h**|
|-|-|

Debido al feedback:
"_El storyboard es poco creíble, un programador de Cobol no debería tener problemas de falta de trabajo._"
Será necesario actualizar el storyboard, un caso que se me ocurre es el de un estudiante recién graduado que esté en búsqueda de trabajo.

**Comment by RukisRo** [comment]
Se ha modificado el StrotyBoard de candidato. Enlace: https://www.canva.com/design/DAGA_tVWk7M/5KPiQskSEwOuN2Dw9T5dZA/edit 
Se ha añadido a la presentación.

**Comment by IsmaelHerrera2000** [comment]
Storyboard actualizado correctamente.
