### ISSUE TITLE
Actualizar Customer Agreement

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#300]
|**Tiempo estimado** |**3h**|
|-|-|

Será necesario actualizar nuestro Customer Agreement para que se adapte al feedback requerido:

- [ ] Desarrollar Términos de servicios
- [x] Uso de Claudette: ¿Qué cláusulas se han eliminado? ¿Cuáles no?
- [ ] Pricing
- [x] SLA: Implicaciones de estas en la implementacion (Cambios en el TCO por personal de soporte adicional por una subida de usuarios)

Además estaría bien redactar un pequeño resumen de cara a la presentación.

**Comment by Francisco-David** [comment]
Terminado en:
https://docs.google.com/document/d/1APmFl6mYxi8IJKhwReHKjHl5NbvXkV3_tu6wxENMgzg/edit#heading=h.v6f92y7saj39
y
https://it-talent-wiki.vercel.app/docs/Coordinaci%C3%B3n/Customer%20Agreement

Se han revisado las clausulas con la herramienta claudette y se han modificado para que sean más justas para ambas partes.
