### ISSUE TITLE
Revisión de suscripciones

### ISSUE THREAD

**Issue by carzarrei** [JaviFdez7/ISPP-G1-Talent#306]
### Descripcción

Se debe implementar/arreglar ...

### Tareas
- Revision Suscripciones
- Resolucion de conflictos

|Estimacion de tiempo|-|
|2,5 h|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Solucionar bug al crear análisis

**Comment by carzarrei** [comment]
**Trabajo realizado:**
Revisión de funcionalidades y resolución de conflictos con develop

**Comment by carzarrei** [comment]
Se ha comproado las principales funcionalidades y se han arreglado varios errores
