### ISSUE TITLE
Cargar datos de candidato (work experience, ...) en vista analisis

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#310]
El candidato tiene información adicional que se debe visualizar en el análisis a diferencia de un análisis que no tenga candidato asociado

TAREAS A REALIZAR:

- [x] Si el análisis tiene un candidato asociado cargar su foto de perfil (en caso de que no se debe seguir cargando la foto de Github)
- [x] Cargar el work experience y los datos de contacto en la vista de análisis si pertenece a un candidato
- [x] Quitar el campo url de Top Recente Repositories que por ahora no carga nada

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Se ha añadido datos del candidato y su work experience si tiene al analisis
- Se ha añadido que la foto cambie a la de usuario si tiene
- Se eliminado el campo url de Top Recent Repositories

**Comment by dangalmar** [comment]
Revisado y correcto
