### ISSUE TITLE
fix work experiencie delete

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#312]
### Descripcción
Se encontró un bug desde el frontend: delete de work experience no borra y da error en backend
No se ha descrito nada mas.

### Tareas
- Investigar e intentar reproducir el bug.
- Solucionar el bug.

|Estimacion de tiempo|-|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by FJMonteroInformatica** [comment]
Estimo tardar alrededor de media hora.

**Comment by FJMonteroInformatica** [comment]
Se ha corregido el bug.
