### ISSUE TITLE
team creator testing

### ISSUE THREAD

**Issue by andresdominguezruiz** [JaviFdez7/ISPP-G1-Talent#315]
### Descripción
Se debe implementar los tests unitarios de crear equipos definidos en https://github.com/JaviFdez7/ISPP-G1-Talent/issues/294

**Estimacion de tiempo**	1h30
Criterios de aceptación
 

- [x] He comprendido la issue o he comentado si algo no quedó claro.

- [x]  He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).

 

- [x] He propuesto mejoras o modificaciones si fuera necesario.

 

- [x] He realizado las tareas y pongo la tarea en revisión.

 

- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by motero2k** [comment]
por favor @andresdominguezruiz  comenta las actualizaciones. Tanto de la implementación como el bug que se encontró en la reunión. Para que quede constancia.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- SetUp funcional
- Primer test de alto coverage de crear equipos

**Trabajo restante:**

- Seguir haciendo pruebas de crear equipos

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- TESTS UNITARIOS DE TEAM CREATOR=> getAll,getById,create,delete.
- Solucionar test E2E
- Encontrar bug con nº de peticiones a Api GraphQL
