### ISSUE TITLE
watch_theory_pill_Theoy Pill on GDPR and UX

### ISSUE THREAD

**Issue by JaviFdez7** [JaviFdez7/ISPP-G1-Talent#320]
|Estimacion de tiempo|30 min|
|-|-|

- [x] BERMEJO SORIA, CARLOS
- [x] CASAL FERRERO, RUBÉN
- [x] DOMÍNGUEZ RUIZ. ANDRÉS
- [x] DOMÍNGUEZ-ADAME RUIZ. ALBERTO
- [x] FERNÁNDEZ CASTILLO, JAVIER
- [x] GALLARDO MARTOS, DANIEL
- [x] HERRERA RAMIREZ, ISMAEL
- [x] IZQUIERDO LAVADO, MARIO
- [x] MATEOS GÓMEZ, FERNANDO JOSÉ
- [x] MERINO PALMA, ALEJANDRO JOSÉ
- [x] MONTERO MARTÍNEZ, FRANCISCO JESÚS
- [x] LÓPEZ MOYANO, ROCÍO
- [x] OTERO BARBASÁN, MANUEL
- [x] VILAPLANA DE TRÍAS, FRANCISCO DAVID
- [x] ZARZUELA REINA, CARLOS

**Comment by Moffinguer** [comment]
@Francisco-David @FJMonteroInformatica se puede cerrar esta issue?

**Comment by FJMonteroInformatica** [comment]
> [@Francisco-David](https://github.com/Francisco-David) [@FJMonteroInformatica](https://github.com/FJMonteroInformatica) se puede cerrar esta issue?

Perdona, se me olvidó marcarla, a pesar de que la había visto hace unos días.

**Comment by Moffinguer** [comment]
Vale, pues se puede cerrar
