### ISSUE TITLE
Revisión de la validación de correo electrónico

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#321]
**Tareas a realizar:**

- Revisar el orden de lanzamiento de errores.
- Revisar dominios de correo admitidos.
- Probar otra API de correos de RapidAPI en lugar de Verifalia.
- Añadir control del escenario negativo en el que los créditos de la API se caducan.

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Comprobación de los errores encontrados en la validación de correo.
- Cambiado el orden de ejecución de errores
- **Nueva API** de validación de correo: _Validect_.

Tiempo invertido: 1 hora
Hash del commit: d39531e11ddbd14082fb2781189661631485ddca

**Comment by dangalmar** [comment]
Revisado y correcto
