### ISSUE TITLE
Crear Demo W10

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#330]
|**Tiempo estimado** |**2h**|
|-|-|

Crear una demo grabada para la presentación de la siguiente semana. Necesario seguir las indicaciones de aumentar contraste de letras claras con fondo negro y hacer zooms. Además, se ha de tener en cuenta el siguiente feedback: 

- Descripción previa al video
- Si en lo que se muestra hay algo nuevo, marcarlo (no quiere decir que haya que mostrar todo lo nuevo)
- Destacar mejoras de UX (píldora teórica).
- Implementación de aspectos legales (P.E: ¿cookies?...)
- Registro con términos y condiciones
- GDPR Compliance: httpS, derecho de olvido...
- NO añadir información redundante en la DEMO (p.ej: edición de campos o registro).
- No hacer uso de imágenes poco realistas para fotos en la demo, si se usan IAs hacer uso de alguna fotorrealista.
- En la DEMO pararse en las funcionalidades core y no mencionar la edición/eliminación de perfiles.
- La DEMO debe estar más orientada al anuncio, que Javi salga en el anuncio como jefe y luego salga igual en la foto de perfil de la DEMO

**Comment by Moffinguer** [comment]
Grabado y presentado
