### ISSUE TITLE
Controlar las vistas y funcionalidades en funcion del plan de suscripcion

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#343]
| Duración | 5 horas |
|----------|--------|

TAREAS A REALIZAR

- [x]  Modificar el useAuthContext para que contenga la suscripcion actual del usuario
- [x]  Modificar vistas y funcionalidades en función del plan de precios del usuario

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha añadido al authcontext el tipo de suscripcion (y por tanto al localstorage)

**Trabajo por realizar**:
- modificar la busqueda de usuario para que use el nuevo tipo de suscripcion

**Comment by albdomrui20** [comment]
**Trabajo realizado:**
- Se ha adaptado el numero de candidatos que puedes hacer en una busqueda segun la suscripcion, haciendo uso del authcontext. Commit: d7ea8c87d776ba46c1b6162e199a4170f4592960

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha hecho que cambie el mensaje de las notificaciones dependiendo del plan. Commit: c920bf9d051c0fe1adfcd9b94f9c64590a318dab
- Se ha arreglado la vista de resultado de busqueda de equipo. Commit: 3b372529a8a53d0e90eb3e094d671125f4c33d70

**Comment by dangalmar** [comment]
Revisado y correcto
