### ISSUE TITLE
Resolver problemas comentados en el feedback de presentaciones

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#344]
| Duración | 2 horas |
|----------|--------|

Resolver problemas encontrados durante el feedback referentes a los usuarios (mirar el feedback de fernando)

**Comment by marizqlav** [comment]
He resuelto:
- Al cambiar la contraseña me permite poner una que tiene menos de 8 caracteres (tambien centrar el formulario al recuadro ya que esta desplazado hacia abajo)
- Cuando una url de imagen no esta permitida te debe salir un mensaje diciendo porque
- Debido a que se tarda mucho el registrar a un candidato por el analisis cuando se registre un candidato debe salir un mensaje que diga "Doing analysis"

**Comment by dangalmar** [comment]
Revisado y correcto
