### ISSUE TITLE
Documentation of testing

### ISSUE THREAD

**Issue by andresdominguezruiz** [JaviFdez7/ISPP-G1-Talent#345]
### Descripción:
Para explicar de forma más detallada el plan de pruebas que vamos a seguir, se creará un documento de formato MD que deberá contener como mínimo los siguientes aspectos:

- Forma de evaluar rendimiento y calidad de los tests
- Cobertura planificada
- Historial de Bugs encontrados, indicando para cada bug: Fecha de aparición, descripción del bug, si se ha solucionado o no, y si se ha solucionado, indicar cuando y cómo se solucionó.

Este documento deberá ser actualizado por todos los miembros (ya sean de backend o de frontend) que estén realizando pruebas.

- [x] He entendido la tarea y he preguntado las dudas que han aparecido
- [x] He sugerido cambios en la tarea
- [x] He creado el documento y he comunicado al grupo sobre su creación y formato de uso.
- [x] He creado la PR
- [x] He acabado la tarea.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Crear documento inicial
- Preparar apartados
- Crear formato de entrada del historial de bugs

**Trabajo restante:**

- Detallar método de evaluación y plan de pruebas
- Añadir bug encontrado

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Definir método de evaluación y formato de cada caso de uso.

**Trabajo sin realizar:**

- Añadir casos de prueba

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Listar casos de uso de Notificaciones/Análisis/Team Creator/Notificaciones/Profesional Experiences

**Trabajo sin realizar:**

- Listar casos de uso del Historial/Subscripciones

**Comment by motero2k** [comment]
@andresdominguezruiz  estaría bien un link al documento.

**Comment by andresdominguezruiz** [comment]
https://docs.google.com/document/d/1KwNqkduOO9UvkFdU3a8arhvljcG3EoJKw9TpD_Gn7E0/edit?usp=drive_link

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Crear primera versión completa del Plan de Pruebas MD

**Comment by RubenCasal** [comment]
Se ha pasado correctamente a MD, se han priorizado los test y se ha planteado una buena forma para saber el estado de los tests. Muy buen trabajo

**Comment by Moffinguer** [comment]
@andresdominguezruiz Puede esta tarea cerrarse?
