### ISSUE TITLE
Proponer riesgos del equipo de marketing

### ISSUE THREAD

**Issue by JaviFdez7** [JaviFdez7/ISPP-G1-Talent#35]
Se deben pensar riesgos que conciernan a los temas tratados en Marketing.

**Comment by IsmaelHerrera2000** [comment]
Se han propuestos diferentes riesgos relativos al Marketing.

**Documento de análisis de riesgos:** https://docs.google.com/document/d/1OFjU3v6Cq_wT_rUfI6fCBQhFGBBuQs_Ol8Kkgtv0_78/edit?usp=drive_link
