### ISSUE TITLE
Terminar Mockups

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#36]
Finalizar mockups a partir de los requisitos y casos de usos.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado (junto a Carlos y Ale):**

- Preparar estilos y formas definitivos del mockup para homogeneizar la información y el estilo
- Empezar a cambiar mockups

**Trabajo sin realizar:**
- Seguir cambiando mockups

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Cambios en notificaciones.
- Cambios en tendencias.

**Trabajo sin realizar:**

- Seguir cambiando mockups.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Vista de ajustes
- Vista mejorada del representante
- Mejorar barra de herramientas añadiendo el icono de los ajustes

**Trabajo sin realizar:**

- Mejorar vista de búsqueda
- Mejorar vista de recomendaciones
- Navegación

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Mejorar vistas de búsqueda y de recomendaciones

**Trabajo sin realizar:**

- Navegación

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Mis análisis
- Mis recomendaciones
- Modo básico del candidato
- Reformateo de la página
- Arreglo de errores

**Trabajo sin realizar:**

- Continuar reformateo
- Revisar trabajo

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Corregir cabeceras de mockups

**Trabajo sin realizar:**

- Navegación

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Revisar estilos y navegación

**Trabajo sin realizar:**

- Acabar navegación y explicar guión de navegación

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Navegación
- Revisión

**Comment by dangalmar** [comment]
Mockups acabados: https://www.figma.com/proto/xcDas6L9vycYjVL2xCDEUh/Talent-test?type=design&node-id=15-165&t=jnt6jfkyI1D8z6zO-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=15%3A165
