### ISSUE TITLE
Crear formularios S3 de candidatos y representantes

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#367]
**Trabajo a realizar:**

- Formulario de candidatos
- Formulario de representantes

**Comment by Moffinguer** [comment]
@carlos-bermejo puede esta issue cerrarse?

**Comment by carlos-bermejo** [comment]
Cuando dejo algo en revisión se entiende que lo he terminado y espero que alguien lo revise. Si alguien lo ha revisado, se puede cerrar. En cualquier caso, el trabajo está terminado.
