### ISSUE TITLE
Documentos entregables de usuarios piloto para el S3

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#369]
**Tareas a realizar:**

### pilots.md
- Actualizar _pilots.md_
- Actualizar plan de acción y registro (incluído en _pilots.md_)
- Actualizar documento de usuarios piloto (incluído en _pilots.md_)
- Actualizar feedback recibido (incluído en _pilots.md_)

### pilotUsersCommitmentAgreement.md
- Incluir _pilotUsersCommitmentAgreement.md_ en la entrega

### PilotUsersPerformanceEvaluation.md
- Actualizar _PilotUsersPerformanceEvaluation.md_

### InformationProvidedByPilotUsers.md
- Actualizar _InformationProvidedByPilotUsers.md_ con nuevo feedback

_⚠Todos los documentos se pueden actualizar a partir de los ya entregados en el S2. Más información en la EV._

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Añadido _pilots.md_
- Añadido _pilotUsersCommitmentAgreement.md_
- Añadido _PilotUsersPerformanceEvaluation.md_
- Añadido _InformationProvidedByPilotUsers.md_

**Trabajo por realizar:**

- Añadir _revision.md_ (aún sin añadir).
- Actualizar _pilots.md_ y _InformationProvidedByPilotUsers.md_ con los datos de Novomás.

**Comment by Moffinguer** [comment]
puede esta issue cerrarse?
