### ISSUE TITLE
Mejorar los estilos del dashboard de busqueda

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#370]
| Duración | 1 horas |
|----------|--------|

Se han encontrado problemas en la representacion de los componentes del dashboard de busqueda

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha modificado para que si el resultado de la búsqueda de candidatos es menos de 3, se coloquen las tablas en una columna, para evitar solapamiento

**Errores detectados**:
- Cuando se realiza una búsqueda, y devuelve candidatos que no están en nuestro historial, estos no se añaden al historial automáticamente, provocando un error.
- En el historial de análisis, todas las entradas me devuelven siempre la última búsqueda realizada

**Comment by dangalmar** [comment]
Revisado y correcto
