### ISSUE TITLE
Trends Backend

### ISSUE THREAD

**Issue by RubenCasal** [JaviFdez7/ISPP-G1-Talent#371]
### Descripcción
En principio se debería hacer que los trends se calcule a partir de que el último trend quede desactualizado (es decir, cuando hacemos el get del trend mas reciente, y dicho trend supera 1 dia desde su cálculo. Se hará un create de un nuevo trend con los datos actuales)

Control de excepciones: la creación del trend al hacer el get debe ser cuando se supere la fecha segun digo anteriormente O CUANDO NO HAY NINGÚN TREND en base de datos (caso inicial)

Para evitar posibles múltiples solicitudes simultáneas. El trend tiene 3 estados: desactualizado, en proceso o actualizado. Cuando un usuario hace el get de un trend, el sistema debe crear el nuevo trend instantáneamente vacío pero con el estado a en progreso. Al terminar los cálculos hace un update de ese mismo trend con todos los datos calculados y cambiando el estado a actualizado

Endpoints esenciales:
Create 
Update
GetCurrentTrend (devuelve el último trend generado: que su estado siempre será en progreso o actualizado)

|Estimacion de tiempo|1 hora 30 minutos|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo unas 5 horas para todas mis tareas).
- [x] He propuesto mejoras o modificaciones si fuera necesario.
- [x] He realizado las tareas y pongo la tarea en revisión.
- [x] He creado la PR necesaria y se le ha vinculado esta issue.

**Comment by Moffinguer** [comment]
@RubenCasal Puede esta tarea cerrarse?

**Comment by carzarrei** [comment]
Se pasó cerrar la issue, todo esta revisado, la cierro
