### ISSUE TITLE
Create Instagram account and first post

### ISSUE THREAD

**Issue by RukisRo** [JaviFdez7/ISPP-G1-Talent#384]

**Comment by RukisRo** [comment]
[Cuenta de instagram ](https://www.instagram.com/it_talent_oficial?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==)

**Comment by Moffinguer** [comment]
Primer post restante

**Comment by IsmaelHerrera2000** [comment]
Primer post creado con éxito, seguiremos publicando e intentando expandirnos.
