### ISSUE TITLE
Hacer de usuarios piloto para el S3 del grupo 7

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#395]
El grupo 7 ya ha desplegado y está a la espera de los usuarios piloto.
Si alguien va a ser usuario piloto, que me avise a mí (Carlos Bermejo) para que os pase su Commitment Agreement para que lo firméis.

Vuestras credenciales (para las dos apps) son: 
- usuario: pilotvisiter
- correo: ittalentofficial@outlook.com
- contraseña: grupo1Pilot1.

El usuario de la app de CyC es un usuario maestro (si queréis otro, dicen que lo creéis con datos realistas).
El enlace a los manuales: https://htld-doc.vercel.app/docs/Manuales%20de%20usuario/7.3.%20Software%20Reviewer%20Guideline%20-%20Sprint%203

Formulario de feedback a rellenar: https://docs.google.com/forms/d/e/1FAIpQLSda1exsoZI3jOJIednAizC8H4gx9w8Q2LoRb0lMl1Rdzw3wtA/viewform

Enlace app CyC: https://frontend-cyc-sprint-3.vercel.app

Enlace app ACAT: https://frontend-acat-sprint-3.vercel.app

(y en sus palabras: "si borráis entidades por favor cread otro de nuevo, con datos realistas, que el s2 se ha suspendido porque estaba borrado todo")

**Comment by carlos-bermejo** [comment]
Ya he terminado como usuario piloto del grupo 7, procedo a enviarles los datos.

**Comment by marizqlav** [comment]
Ya he terminado como usuario piloto del grupo 7, procedo a enviarles los datos.

**Comment by motero2k** [comment]
He sido usuario piloto del grupo 7. He enviado el formulario.
