### ISSUE TITLE
Buscar nuevos usuarios pilotos para que prueben la aplicación 

### ISSUE THREAD

**Issue by JaviFdez7** [JaviFdez7/ISPP-G1-Talent#397]
### Descripcción
El objetivo es conseguir usuarios pilotos (empresas o usuarios independientes) para que prueben la aplicación de S3

Enlace a la app: https://ispp-g1-talent-frontend.vercel.app

Manual de usuario: 
- Candidato: [Manual de Usuario (Candidato) - D3.pdf](https://github.com/JaviFdez7/ISPP-G1-Talent/files/15108933/Manual.de.Usuario.Candidato.-.D3.pdf)
- Representante: [Manual de Usuario (Representate) - D3.pdf](https://github.com/JaviFdez7/ISPP-G1-Talent/files/15108934/Manual.de.Usuario.Representate.-.D3.pdf)

 

Formularios:
- Candidato: https://forms.office.com/e/888t1ExFbr
- Representante: https://forms.office.com/e/7aunSCG4d5

|Estimacion de tiempo|1 hora 30 min|
|-|-|

**Comment by JaviFdez7** [comment]
Contacto con usuario piloto independiente (nombre: Antonio Cortés Jiménez) a través de WhatsApp
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/100673872/793fa8d1-869c-4367-b823-293d2b1b7e80)

Estado: esperando respuesta

**Comment by carzarrei** [comment]
Usuario piloto: Carlos Germá García
Estado laboral: contratado en una empresa de informática y estudiando grado universitario de informática
Tipo: Programdor SQL
Contacto con usuario piloto independiente a través de WhatsApp:
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72513946/7aae1ceb-49dc-40d8-a332-f986d5ef96e0)
Estado: esperando respuesta

**Comment by carzarrei** [comment]
Usuarios pilotos: Grupo de desarrolladores de IR Soluciones Sevilla
Tipo: Equipo de desarrollo software
Contacto con usuarios pilotos independientes a través de WhatsApp:
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72513946/f917d46c-0b6f-4f0d-908b-14e975449812)
Estado: esperando confirmación

**Comment by carzarrei** [comment]
Usuario piloto: IR Soluciones
Tipo: Empresa
Contacto con usuario piloto a través de Correo electrónico:
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72513946/ea53a9a5-5bca-4320-aec5-a819cea8b71e)
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72513946/e4e8eab9-f1c1-4af6-a2a5-8c2150fed391)
Estado: esperando confirmación tras la respuesta.

**Comment by carzarrei** [comment]
Actualización de estado de usuarios piloto: 
IR soluciones a confirmado su colaboración, el encargado ya se ha registrado como representante en la aplicación y cuando pruebe las diferentes funcionalidades proporcionará el feedback
![image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/72513946/a992bdf8-05f6-4109-a07e-31f3119d2527)
