### ISSUE TITLE
Actualizar el documento de análisis de costes

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#40]
Será necesario actualizar el documento de análisis de costes y el pricing, teniendo en cuenta el feedback de esta semana:

- Si es un elemento el que nos diferencia de la competencia, el pricing debería ir enfocado a este.
- El TCO debe estar expresado de manera mensual no anual.
- Los análisis de costes son más inteligibles en forma de tabla.
- Los costes de herramientas y/o licencias de pago (por ejemplo github) deben ser tenidos en cuenta. Si es un servicio gratuito se debe exponer la existencia de un plan si este deja de serlo.
- Al proponer precios debe quedar claro los beneficios que se están sacando (TCO).
- No poner precios por hora para cada rol. Se debe poner la hora básica de servicio y realizar multiplicadores (por ejemplo, un jefe de proyecto suele cobrar un x2.5 sobre la básica).
- Hay que asumir los costes de github y tenerlos en cuenta. Si asumimos que es gratuita la licencia, ¿Qué pasaría si no? ¿Cuántas github action usaremos al mes?

- Se debe dejar claro de dónde sale el cálculo de precios y cuál es el beneficio que se saca de estos.

**Comment by FJMonteroInformatica** [comment]
**Trabajo realizado:**

- Actualización de la estimación general de costes.

**Comment by IsmaelHerrera2000** [comment]
Se han añadido los cambios respecto al feedback correctamente.

**Documento de análisis de costes**: https://docs.google.com/document/d/1LVxWJ0hOVtFfyaZ9_Y2q4fSKcFRQzmSuHVyDmzmpWIY/edit?usp=drive_link
