### ISSUE TITLE
Resolver problemas del feedback del nav y notificaciones

### ISSUE THREAD

**Issue by marizqlav** [JaviFdez7/ISPP-G1-Talent#400]
| Duración | 1 horas |
|----------|--------|

TAREAS A REALIZAR

- [x] Cambiar "my analysis" por "Analysis"
- [x] Corregir encuadre de información de usuario (sobre todo la foto de perfil) e indicar el plan de precios actual
- [x] El modal de borrado de notificaciones te dice de borrar el working experience por lo que debe cambiarse

| Duración | 1.5 horas |
|----------|--------|

TAREAS A REALIZAR

- [x] Poner que cada accion de creacion, modificacion y borrado tenga un mensaje de creacion exitosa
- [x] Indicar mediante un mensaje que no hay elementos en una lista de historial cuando no lo haya

**Comment by marizqlav** [comment]
He realizado el cambio de nombre de "my analysis" por "Analysis" en el Navbar y en un test ya que tenía el nombre. he modificado el mensaje que sale por pantalla cuando se le da una url incorrecta para que tambien avise de la terminación de la url, he modificado el nombre del modal para que salga que ha eliminado una notification y he cambiado el numero del precio de los planes de representante.

**Comment by dangalmar** [comment]
Revisado y correcto
