### ISSUE TITLE
Terminar vista de candidato arreglar pequeños errores

### ISSUE THREAD

**Issue by albdomrui20** [JaviFdez7/ISPP-G1-Talent#403]
| Duración | 3 horas |
|----------|--------|

TAREAS A REALIZAR

- [x] Que la vista de análisis del candidato se visualice con el mismo formato que el de la vista de análisis
- [x] Visualizar los tokens de actualización que le quedan a un candidato y el tiempo que le queda para actualizarse los tokens
- [x] Resolver problema de actualizacion de foto descrita en el feedback

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Añadido visualización del número de tokens de actualización restantes (se ha modificado subscription del authContext para que no devuelva solo el tipo, sino el objeto entero). Commit: f4a1e29d9678e0967e0a9c680e7fec9101002628

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Se ha modificado la vista de detalles de candidato para que el análisis se muestre como en en el AnalysisDashboard, gáficas incluidas. Commit: 15919461dcb4ff4d22df7a6692ed80935a1c8557
- Se ha modificado algunos textos del AnalysisDashboard para que se vean más claramente. Commit: 15919461dcb4ff4d22df7a6692ed80935a1c8557

**Comment by albdomrui20** [comment]
**Trabajo realizado:**

- Se ha arreglado los problemas detectados por los usuarios pilotos al modificar la foto de usuario. Commit: ab585b8db72f80ffb70aaa8cd8282acbfe796672

**Comment by dangalmar** [comment]
Revisado y correcto
