### ISSUE TITLE
Mejorar la vista de dashboard de búsqueda y resolver pequeños errores

### ISSUE THREAD

**Issue by alemerpal** [JaviFdez7/ISPP-G1-Talent#407]
| Duración | 5 horas |
|----------|--------|

TAREAS A REALIZAR

- [x] Mejorar vista de búsquedas (utilizar si se puede la librería de gráficas chartjs)
- [x] Arreglar error de experiencia (redondear a años)
- [x] Incluir la opción de añadir a favoritos desde el dashboard como en la vista de análisis

**Comment by dangalmar** [comment]
Revisado y correcto
