### ISSUE TITLE
Preparar presentación Final(10 minutos)

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#408]
### Descripción
Preparar la presentación de 10 minutos para la siguientes clase, teniendo en cuenta el feedback y la estructura del siguiente documento en la week10:
https://docs.google.com/spreadsheets/d/1vjDdajdJHCcg5G8w3haS24YhxKHV0oWbAG94f7oykro/edit?usp=drive_link

|Estimación de tiempo|4 horas por persona|
|-|-|

**Comment by motero2k** [comment]
Se han cambiado las dipapositivas para dejarlo en 10 minutos

**Comment by motero2k** [comment]
se ha actualizado los costes. Mañana se actualizaran las graficas de coste vs beneficio.
