### ISSUE TITLE
Preparar presentación Marketing(5 minutos)

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#409]
### Descripción
Preparar la presentación de 5 minutos sobre Marketing para la siguientes clase, teniendo en cuenta el feedback y la estructura del siguiente documento en la week10:
https://docs.google.com/spreadsheets/d/1vjDdajdJHCcg5G8w3haS24YhxKHV0oWbAG94f7oykro/edit?usp=drive_link

|Estimación de tiempo|2 horas por persona|
|-|-|

**Comment by Moffinguer** [comment]
A raiz de esta issue, ha sido necesario incluir en el indexador de Google para poder usar el SEO
