### ISSUE TITLE
Actualizar sección Pricing del Customer Agreement

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#427]
### Descripción
De acuerdo con el feedback recibido por el profesor Antonio Ruiz Cortés: 
"Customer Agreement. La sección de "Precios"" debería ser una párrafo donde se indica que la politica de precios estará disponible en <url del pricing>."
Se deberá solucionar en el documento correspondiente.

|Estimación de tiempo|15 minutos|
|-|-|

**Comment by Francisco-David** [comment]
Ya está la pull request con los cambios a develop con Fernando como revisor
