### ISSUE TITLE
matriz RACI

### ISSUE THREAD

**Issue by RukisRo** [JaviFdez7/ISPP-G1-Talent#43]
Realizar una matriz RACI con los responsables de cada área para añadir a la presentación. La matriz debe basarse en los siguientes documentos: 

- https://docs.google.com/spreadsheets/d/1tbn0yECFhfqK9HQ1bGH_qjl9ec1Wyt-hHGDYzokBSV8/edit#gid=0 
- https://docs.google.com/document/d/1gFbMyKrye_CBdTLo17ioBoWJBZcXWFqkQFJblD0cyLA/edit#heading=h.ebgmx8b5zfn6

**Comment by motero2k** [comment]
Revisado y correcto
