### ISSUE TITLE
Permitir cargar la imagen de perfil desde local (Colaboración con backend)

### ISSUE THREAD

**Issue by alemerpal** [JaviFdez7/ISPP-G1-Talent#430]
Se realizará una rama en la que se implementará tanto el backend como el frontend. El miembro asignado a esta tarea deberá ponerse de acuerdo con el miembro de backend para realizar esta funcionalidad.

**Comment by dangalmar** [comment]
No se ha podido megear ya se hara otra issue para arreglar los problemas
