### ISSUE TITLE
Revisión final de la de validación de correo

### ISSUE THREAD

**Issue by carlos-bermejo** [JaviFdez7/ISPP-G1-Talent#431]
**Trabajo a realizar:**

- Revisar validadores del formulario de registro (candidato y representante).
- Revisar restricciones de la API de validación (candidato y representate).
- Prueba de correos: @us.es, @outlook.com, @gmail.com, @hotmail.com.

**Comment by carlos-bermejo** [comment]
**Trabajo realizado:**

- Reducción del criterio de la validación de correo para aceptar más correos.
- Prueba con correos: @us.es, @outlook.com, @gmail.com, @hotmail.com.
- Cambio en la forma de mostrar aviso de error de validación (antes no se borraba el texto de error nunca).

Hash del commit: 34b854fabcdd942c11b2192e6d1ca63b477d1330

**Comment by dangalmar** [comment]
Revisado y aceptado
