### ISSUE TITLE
Implementar la funcionalidad de "¿Olvidaste la contraseña?" (Colaboración con backend)

### ISSUE THREAD

**Issue by marizqlav** [JaviFdez7/ISPP-G1-Talent#432]
Se realizará una rama en la que se implementará tanto el backend como el frontend. El miembro asignado a esta tarea deberá ponerse de acuerdo con el miembro de backend para realizar esta funcionalidad.

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Flujo de cambio de contraseña desde backend acabado (solicitar cambio de contraseña y cambiar contraseña)

**Trabajo restante:**

- Enviar correo con el enlace para cambiar la contraseña

**Comment by marizqlav** [comment]
Ya estás hechas las vistas y las funcionalidades de frontend, a falta de cambiar el swal que sale para que te muestre el tiempo y que Andrés termine de hacer el correo.

**Comment by dangalmar** [comment]
Revisado y mergeado por @RubenCasal y yo
