### ISSUE TITLE
Arreglo de bugs encontrados en frontend

### ISSUE THREAD

**Issue by albdomrui20** [JaviFdez7/ISPP-G1-Talent#434]
Durante estos últimos días se han encontrado los siguientes bugs que se deben solucionar

- [x] En la búsqueda de equipos el selector de número candidatos a buscar debe tener el valor 2 por defecto
- [x] Solucionar error que se produce cuando un representante realiza un analisis de un candidato ya tiene análisis (hablar con Rubén, ya que fue quién encontró el error)
- [x] Solucionar error que ocurre en el historial de búsqueda cuando una búsqueda se añade a favoritos y en la misma vista se intenta eliminar (no se elimina)
- [x] Poner en el mensaje de la APIKey de analisis que este es opcional (tanto en análisis que hace el representante como el análisis de candidato)
- [x] Que los trends sean accesibles solo por el plan de suscripcion adecuado

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha protegido Trends según la suscripción. Commits:
  - a2de04fc98c93f060276a9c04d65e63d60bf8f1f
  -e4c8e943e521c067d0ab3cc955b8cfdbb0fac085
- Se ha añadido texto para indicar que el uso de la APIKey de Github es opcional. Commit: d2c98d550bad8ae5b00c405b88e4ae48a0539254
- Se ha establecido que el numero de candidatos con los que empieza la búsqueda es 2. Commit: 7a5f927e1a9b7b348fb7271598620f9e3d32c9f6

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha arreglado el error de análisis indicado por Rubén. Commit: 8e93a6deaa00872e77dceac067b58febb9447c3d

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha arreglado el error de favoritos en el historial de análisis. Commit:0731f51ce638de71a4bad4a339016c1fc76a51f9

**Comment by dangalmar** [comment]
Revisado y correcto
