### ISSUE TITLE
Recoger feedback 30/04

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#435]
### Descripción
Apuntar el feedback dado durante las presentaciones de la clase del 30/04 para aplicarlo en la semana 12.

|Estimacion de tiempo|1 hora y 30 minutos|
|-|-|

**Comment by Francisco-David** [comment]
Ya realizado en https://it-talent-wiki.vercel.app/docs/Control%20y%20Presentaciones/Informes%20de%20Feedback
