### ISSUE TITLE
Revisar que todo el feedback de la semana está hecho

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#44]
Revisar que todos los cambios y comentarios de mejora del proyecto (feedback) han sido considerados y/o están reflejados en la presentación. 
(Cotejar con el Informe de Feedback)

**Comment by Moffinguer** [comment]
@Francisco-David Debes de cerciorarte de que se siguen las directrices del feedback y las reglas de los documentos que aparecen en el documento de criterios de suspensión

**Comment by Moffinguer** [comment]
Se está trabajando en crear una lista de consecuencias del feedback en el proyecto
https://docs.google.com/document/d/1-JdmIlDlgtamA9A6RrK8hMSK3KW3ZWJ4nYqbhNbHEMg/edit#heading=h.tyjcwt

**Comment by motero2k** [comment]
Se ha revisado y entregado el entregable DP. Muy bien!!
