### ISSUE TITLE
Anuncio/DEMO

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#443]
Intentar realizar un anuncio a la vez que DEMO de esta manera podría quedar menos repetitivo. Javi se encargará de esto. Es decir, en nuestro caso podría funcionar mejor un anuncio en el que se vean claramente las funciones de nuestra aplicación. El audio debe ser mejorado en el anuncio (arreglar eco), aclararlo lo mas posible (o volver a grabarlo encajarlo en el video).

**Comment by JaviFdez7** [comment]
demo final https://www.youtube.com/watch?v=pO7UgLfbFnk
