### ISSUE TITLE
Publicar contenido en Tik Tok

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#447]
Publicaciones que tienen como objetivo farmear interacciones con contenido más informal(aún así, marcaremos fechas en las que se subirá contenido formal, como anuncios y demos).

**Comment by carzarrei** [comment]
Se ha creado la cuenta de TikTok de IT Talent, 
Usuario: it_talent_oficial

**Comment by carzarrei** [comment]
Publicado el primer video en tiktok con el ultimo anuncio.

**Comment by carzarrei** [comment]
Se ha publicado el primer meme en TikTok

**Comment by carzarrei** [comment]
Creado el 2º meme para tiktok
