### ISSUE TITLE
Preparación contenido RRSS Semana 6/5 (Post + historias)

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#448]
Seguir publicando contenido en RRSS. Instagram será nuestra principal red social y la más seria.

**Comment by RukisRo** [comment]
Contenido programado para las siguientes fechas:
P1: 6/5 -> ¿Qué es IT TALENT? Video de Javi y Lolo explicándolo
P2: 8/5 -> ¿Qué hace una empresa para encontrar candidatos? Video de Javi y Lolo explicándolo
P3: 10/5 -> ¿Se pueden formar equipos completos? Video de Javi y Lolo explicándolo

Las publicaciones se realizarán en torno a las 14:30* siguiendo con la planificación de publicaciones
