### ISSUE TITLE
cartel para WPL

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#452]
### Descripcción

Según ev hay que realizar un cartel con el nombre de nuestro grupo. una breve descripción y el enlace/QR a nuestra landing page

**Comment by motero2k** [comment]
Esta es la versión que propongo.

![Image](https://github.com/JaviFdez7/ISPP-G1-Talent/assets/91433995/66a5cba0-053b-4686-8135-622b07fc4303)

**Comment by IsmaelHerrera2000** [comment]
Carteles enviados
