### ISSUE TITLE
Checkpoint de control de tiempo en diapositivas

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#46]
Buscar que tiempo se le quiere dar a cada sección de la presentación. Establecer unas diapositivas de control (al menos 4) para saber en que minuto se deberia ir por esas diapositivas.

De esta tarea se encargará el presentador Fernando, ayudado por los miembros del equipo de presentaciones y revisado por el Team Leader y el cordinador del grupo.

**Comment by Moffinguer** [comment]
Se considera relevante que se está realizando un guion con toda la info a presentar, dicha tal y como se quiere.
https://docs.google.com/document/d/1cx7vq2mJfRulYn9G7ouKBF6azqCOqpz2FmNmCLUDy-U/edit

Faltaría por añadir al guion el texto referente a los costes y los riesgos.

Habrán 4 puntos de control.
- Hasta el elevator pich, antes de los competidores
- Uno antes de los costes
- Uno tras hablar del equipo y el desarrollo
- Uno tras los mockups

@motero2k @JaviFdez7

**Comment by Moffinguer** [comment]
Esta tarea se ha completado y se está probando con la simulacro

**Comment by motero2k** [comment]
Tarea comprobada, la semana que viene reajustamos respecto a la exposicion en clase. Buen trabajo!
