### ISSUE TITLE
Resolver feedback de los usuarios piloto

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#467]
TAREAS A REALIZAR

- [x] Solucionar error del localStorage. Si el userId o el token no corresponde a un usuario de la base de datos se debe desloguear automáticamente.
- [x] Pantallazo en búsqueda de equipos. Al usuario le salió un pantallazo cuando especificó "Technologies" pero no especificó "Languages". Este problema se puede deber a falta de validaciones en frontend.
- [x] Ordenar los repositorios de un candidato o análisis en base al número de estrellas y forks. Es buena idea que aparezcan primero los que más estrellas y forks tienen.
- [x] Aumentar un poco el texto de las vistas de gráficas y cambiar el color de las letras para que sea blanco y no gris. Esto servirá para que se vea mejor todo.
- [x] Quitar la validación de que la fecha de final sea anterior a la fecha actual ya que ha sido solicitado por los usuarios piloto.

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha puesto el texto de las gráficas en blanco y se a aumentado un poco el tamaño. Commits:
  - representante: f021723854e18ae721ab878bfe2b1cfca5555694
  - trends: 18a461589ec1f27e147a3a5437044aa581737289
  - candidato: 66b502d4b40f7b735743050fc9e0074000824870
- Se ha añadido que se ordenen los repositorios de los análisis por estrellas y forks, (de mayor a menor). Commits:
  - representante: f021723854e18ae721ab878bfe2b1cfca5555694
  - candidato: 66b502d4b40f7b735743050fc9e0074000824870

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha añadido validaciones al formulario de búsqueda, de manera que todos los campos son obligatorios. Commit: a571df8b9f736c5c4df28c47fefda847b09c007e

**Comment by albdomrui20** [comment]
**Trabajo realizado**:
- Se ha hecho para que si se modifica el valor del token o userId en localStorage, el usuario se vea deslogeado. Commit: 226d5379c50162e4612d28787a87c06dd4478b08

**Comment by dangalmar** [comment]
Revisado y correcto
