### ISSUE TITLE
Final slides

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#470]
### Descripcción

Preparar las diapositivas del lanzamiento de la app y estudiar las presentaciones.
### Tareas
- Quitar las palabras que no entienden las personas ajenas a ISPP
- Poner diapositiva de redes sociales
- Pensar en killer opener
- Estudiar y repasar la presentación

|Estimacion de tiempo|12h (en 2 semanas)|
|-|-|

### Criterios de aceptación
- [x] He comprendido la issue o he comentado si algo no quedó claro.
- [x] He dado la estimación de tiempo.
- [x] He propuesto mejoras o modificaciones si fuera necesario.

**Comment by motero2k** [comment]
Los vienes buscamos una forma de que el publico conectara con nuestra presentación. Tal vez repartamos unos folletos con estadísticas de los usuarios de la clase con toda la info de nuestra app.

**Comment by motero2k** [comment]
Ayer estuve repasando y practicando la primera parte de la presentación. Tenemos que ver si cambiar el killer opener. Hoy he quitado las palabras extrañas y arreglado cositas de las diapositivas.

**Comment by motero2k** [comment]
Hemos tenido una reunión en la que hemos decidido el guion definitivo. Lo pasaré a limpio después.

**Comment by motero2k** [comment]
Falta mejorar el apartado de preguntas, pero esta es una primera buena versión de la definitiva.
[guion wpl.pdf](https://github.com/JaviFdez7/ISPP-G1-Talent/files/15341574/guion.wpl.pdf)

**Comment by RukisRo** [comment]
Se han modificado algunas diapositivas
