### ISSUE TITLE
Finalizar análisis de competencia

### ISSUE THREAD

**Issue by dangalmar** [JaviFdez7/ISPP-G1-Talent#52]
Realizar un análisis de la competencia más exahustivo teniendo en cuenta el feedback y la píldora teórica.

IMPORTANTE:
Indicar las **fuentes utilizadas** para la búsqueda de competidores y clasificar los competidores en los **3 tipos de competidores** indicados en la **píldora**.

**Comment by albdomrui20** [comment]
Trabajo realizado (17/02) :
- Se ha indicado el tipo de competencia que es cada una.
- Las fuentes (palabras clave, métodos, páginas y herramientas) están indicadas.
- Se ha añadido un competidor.

**Comment by dangalmar** [comment]
Documento realizado: https://docs.google.com/document/d/1ldVasD9iDRgeDisA5cFJ-MDEHe-cWkAEvr3M2Lc86Cs
