### ISSUE TITLE
Actualizar checkpoints para la presentación 27/02/2024

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#60]
La exposición de esta semana durará 15 minutos, además se han dado porcentajes exactos, por lo tanto podemos dividir la presentación en:

- 15-20%: Inicio y desarrollo del modelo de negocio.
- 10%: Gestión de usuarios pilotos.
- 15%: Prototipo con lo desarrollado en la primera semana del sprint 1.
- 40-45%: Retrospectiva de la primera semana:
- 15%: Planificación o re-planificación.
- Diapositiva de autodefensa.

**Comment by Francisco-David** [comment]
Terminados en la estructura en:

https://docs.google.com/document/d/1cx7vq2mJfRulYn9G7ouKBF6azqCOqpz2FmNmCLUDy-U/edit

**Comment by IsmaelHerrera2000** [comment]
La estructura se ajusta al feedback.
