### ISSUE TITLE
Buscar que nos ofrece la api de github

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#64]
Basarse en el documento de requisitos. #58 
|**Tiempo estimado** |**2h**|
|-|-|

- [ ] Hacer peticiones a GitHub con las querys de discord y guardar los JSONs para poder hacer tests.
- [ ] Analizar y proponer otras querys que ofrezcan información relevante para analizar a los candidatos.

**Comment by RubenCasal** [comment]
Nombre de usuario: dmananes
Url Avatar: https://avatars.githubusercontent.com/u/6003619?u=c397d11f3ba9c80e048a7eec7406f219458082ab&v=4 
Seguidores: 6
Repositorios propios:  7
Número de repositorios contribuidos con commits: 0
Número de repositorios contribuidos con pullRequests: 1
10 Repositorios más recientes:
- BangleApps: https://github.com/dmananes/BangleApps, Stars: 0, Forks: 0
- vue-native-notification: https://github.com/dmananes/vue-native-notification, Stars: 0, Forks: 0
- SmartCola: https://github.com/jameshedaweng/SmartCola, Stars: 0, Forks: 0
- morsetalk: https://github.com/Kr0n0-Misc/morsetalk, Stars: 0, Forks: 0
- lighttalk: https://github.com/Kr0n0-Misc/lighttalk, Stars: 0, Forks: 0
- black-point: https://github.com/dmananes/black-point, Stars: 0, Forks: 0
- black-point: https://github.com/jameshedaweng/black-point, Stars: 0, Forks: 1
Top 5 Languages Used:
JavaScript
Java
TypeScript
Tecnologías:
- acorn
- eslint
- eslint-config-airbnb-base
- eslint-plugin-import
- npm-watch
- babel-preset-env
- babelify
- browserify
- standard
- uglify-js
- react
- react-native
- react-native-blur
- react-native-linear-gradient
- react-native-maps
- react-native-modal
- babel-jest
- babel-preset-react-native
- jest
- react-test-renderer

**Comment by motero2k** [comment]
todo ok para la primera version. Buen trabajo.
