### ISSUE TITLE
analysis testing v1

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#72]
### Explicación
Versión preeliminar para los tests del sprint 1.
- Propuesta de tests S1 con alto coverage.
- Implementar tests.

### Tareas
- [x] He comprendido la issue o he comentado si algo no quedó claro
- [x] He dado la estimación de tiempo (Teniendo en cuenta que tengo 5 horas para todas mis tareas)
- [x] Se ha realizado el trabajo y pongo la tarea en revisión

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- Probando a hacer testing E2E utilizando mockups .
- Intentando hacer test sobre loginUser

**Trabajo sin realizar:**

- Hacer testing sobre Historial

**Comment by andresdominguezruiz** [comment]
**Trabajo realizado:**

- E2E test sobre login de usuario hecho
- Método para analizar coverage hecho

**Comment by motero2k** [comment]
Revisado y cerrado
