### ISSUE TITLE
analysis frontend navigation

### ISSUE THREAD

**Issue by motero2k** [JaviFdez7/ISPP-G1-Talent#73]
Realizar la navegación del frontend según explicó Daniel. Después hacer una primera versión del dashboard de analisis.
Debe haber secciones aunque solo implementemos la de GitHub en la primera iteración.

**Comment by carlos-bermejo** [comment]
**Tareas por realizar:**

- Crear página principal
- Enrutamiento de la aplicación
- Primera versión del dashboard

**Comment by carlos-bermejo** [comment]
**Se especifica que el alcance de la tarea cubre solo la navegación del frontend respecto a los representantes**

**Comment by carlos-bermejo** [comment]
**Tareas realizadas:**

- Enrutamiento "placeholder" de representante

**Tareas por realizar:**

- Primera versión del dashboard
