### ISSUE TITLE
Despliegue del código S1

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#76]
Desplegar el código de la aplicación.

**Comment by Moffinguer** [comment]
Estudio de como desplegar los servicios y bases de datos.
Hasta el momento se ha descubierto lo siguiente:
- Podemos lanzar los microservicios en paralelo desde la misma maquina
- Necesitamos un archivo de configuración .yml
- Para usar MongoDB se necesita subscribirnos a una maquina a parte

**Comment by Moffinguer** [comment]
La configuración del archivo .yml se puede generar gracias a la documentación de [app-engine](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime?hl=es-419)
Hay [plantillas](https://github.com/GoogleCloudPlatform/nodejs-docs-samples) de estas configuraciones, podemos tomarlas como referencia
Se ha creado una BBDD con MongoDB en la [nube](https://cloud.mongodb.com/v2/65d8cda84d6af9776231daff#/overview), como subscripción. Si se quiere acceder como colaborador se necesita una cuenta.

**Comment by Moffinguer** [comment]
Tareas:

- [ ] Crear un despliegue con comandos con el proyecto en develop
- [ ] Crear una subrutina con github-actions para poder desplegarlo cada vez que se lanze a una rama predeterminada. Denominemosla _italent-pro_

**Comment by Moffinguer** [comment]
Esta es la url que se debe de indicar en producción al conectarse con la base de datos en remoto:

mongodb+srv://fernandomateosfermatgom:<password>@ispp-db.c0mwv5n.mongodb.net/?retryWrites=true&w=majority&appName=ispp-db

<password>: Contraseña de la cuenta que aloja la máquina. Aún no se va a proporcionar

**Comment by Moffinguer** [comment]
\<password\>:"eL6F=.BM!MtSX;W"

**Comment by Moffinguer** [comment]
La aplicación se puede desplegar con los microservicios en paralelo, testeado en local.
Al lanzarlo en remoto funciona también bien.

Error al lanzarlo en remoto:
-> Los comandos "vite" y "ts-node" parecen no "instalarse" o funcionar. No se obtiene una traza clara. Simplemente avisa de que no se instalan.

En el momento de sobrepasar este problema se puede desplegar correctamente
