### ISSUE TITLE
Actualizar el guion de la presentación a la W5

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#87]
Será necesario actualizar el guion y la estructura de este para adaptarnos al nuevo esquema de presentación:

- 15% INTRODUCCIÓN proyecto:
     - Killer Opener
     - Elevator Pitch
     - Resumen Análisis de competidores
     - Resumen de TCO:
         - Capex: coste desarrollo,  licencias, personal de la empresa, portátil, amortización por varios projects…
         - Opex: gastos hosting e infraestructura, customs, mantenimiento, ventas-marketing-anuncios, maquinaVM en la nube, mejoras, support, ventas para el cliente, copilot
         - PORCENTAJE DE CAPEX VS OPEX EN GRANDE.
     - Situación actual del presupuesto gastado vs TOTAL esperado.
     - Estimaciones corto (4 /6 meses) y largo (12/24 meses) plazo de ingresos y medir el número de usuarios e ingresos divididas en pesimistas, optimistas y realistas.
     - Refinar los roles de equipo, composición y jerarquía.
     - Estado de cumplimiento del CA.

- 15% DEMO FINAL del sprint 1 con casos de uso core terminados

- 40 % RETROSPECTIVA del sprint 1:
     - Rendimiento del equipo (mejora/empeora, fórmulas) . POR MIEMBRO.
     - Codacy, Sonar, algo de la Gestión de la Calidad del código.
     - Gestión de riesgos.
     - Control del rendimiento de las medidas tomadas. Si se ha encontrado un nuevo problema, proponer la solución y decir cómo se medirá el rendimiento cuando se emplee en el próximo sprint.
     - Lecciones aprendidas.
     - Reloj de avance del proyecto / Clockify.
    
- USUARIOS PILOTO:
     - Gestión de usuarios; feedback… a nivel mensual.
     - Cuando vamos a entregar el MVP y cuando necesitamos el feedback + planificar el segundo sprint en este asunto
 
- PLANIFICACIÓN:
     - De esta semana y el sprint 2. ¿Hará falta re-planificación?
     - Planificación del 3. ¿Hará falta re-planificación?

- REPORT DE USO DE IA

- Última diapositiva: QR Landingpage. Con nuestros datos de contacto.

**Comment by Francisco-David** [comment]
Ya realizado sobre:

https://docs.google.com/document/d/1cx7vq2mJfRulYn9G7ouKBF6azqCOqpz2FmNmCLUDy-U/edit?pli=1

**Comment by IsmaelHerrera2000** [comment]
Guion terminado correctamente.
