### ISSUE TITLE
Crear Action de despliegue automático

### ISSUE THREAD

**Issue by IsmaelHerrera2000** [JaviFdez7/ISPP-G1-Talent#99]
Crear un GitHub Action que permita desplegar la aplicación automáticamente cada vez que exista una nueva realese.

**Comment by Moffinguer** [comment]
Debido a problemas con creditos, y que es posible que se tenga que cambiar a la persona que despliegue.
Es problemático usar un action automático, por lo que es mejor simplemente formar a la persona a usar gcloud y que se despliegue llegado el momento. @IsmaelHerrera2000

**Comment by IsmaelHerrera2000** [comment]
Se cancela el despliegue automático debido a la falta de créditos.
